# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fukuro_common/SpeedTuningRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import fukuro_common.msg

class SpeedTuningRequest(genpy.Message):
  _md5sum = "3094cde591fc0e253ec2416e29f6fff2"
  _type = "fukuro_common/SpeedTuningRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Parameter linear
Parameter angular

================================================================================
MSG: fukuro_common/Parameter
float64 kp
float64 ki
float64 kd"""
  __slots__ = ['linear','angular']
  _slot_types = ['fukuro_common/Parameter','fukuro_common/Parameter']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       linear,angular

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SpeedTuningRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.linear is None:
        self.linear = fukuro_common.msg.Parameter()
      if self.angular is None:
        self.angular = fukuro_common.msg.Parameter()
    else:
      self.linear = fukuro_common.msg.Parameter()
      self.angular = fukuro_common.msg.Parameter()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.linear.kp, _x.linear.ki, _x.linear.kd, _x.angular.kp, _x.angular.ki, _x.angular.kd))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.linear is None:
        self.linear = fukuro_common.msg.Parameter()
      if self.angular is None:
        self.angular = fukuro_common.msg.Parameter()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.linear.kp, _x.linear.ki, _x.linear.kd, _x.angular.kp, _x.angular.ki, _x.angular.kd,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.linear.kp, _x.linear.ki, _x.linear.kd, _x.angular.kp, _x.angular.ki, _x.angular.kd))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.linear is None:
        self.linear = fukuro_common.msg.Parameter()
      if self.angular is None:
        self.angular = fukuro_common.msg.Parameter()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.linear.kp, _x.linear.ki, _x.linear.kd, _x.angular.kp, _x.angular.ki, _x.angular.kd,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fukuro_common/SpeedTuningResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SpeedTuningResponse(genpy.Message):
  _md5sum = "b731fe652071ec695a1ec7ac77e39ebe"
  _type = "fukuro_common/SpeedTuningResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool tune_ok
"""
  __slots__ = ['tune_ok']
  _slot_types = ['bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       tune_ok

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SpeedTuningResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.tune_ok is None:
        self.tune_ok = False
    else:
      self.tune_ok = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.tune_ok
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.tune_ok,) = _get_struct_B().unpack(str[start:end])
      self.tune_ok = bool(self.tune_ok)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.tune_ok
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.tune_ok,) = _get_struct_B().unpack(str[start:end])
      self.tune_ok = bool(self.tune_ok)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
class SpeedTuning(object):
  _type          = 'fukuro_common/SpeedTuning'
  _md5sum = 'cd170060ae0088446fa7f04a91313ea5'
  _request_class  = SpeedTuningRequest
  _response_class = SpeedTuningResponse
