(cl:in-package fukuro_common-msg)
(cl:export '(ROBOT_NAME-VAL
          ROBOT_NAME
          BALL_VISIBLE-VAL
          BALL_VISIBLE
          OBSTACLE_VISIBLE-VAL
          OBSTACLE_VISIBLE
          FRIEND_VISIBLE-VAL
          FRIEND_VISIBLE
          AVAILABLE-VAL
          AVAILABLE
          SET_OBSTACLE-VAL
          SET_OBSTACLE
          POSITION-VAL
          POSITION
          TEAMMATES-VAL
          TEAMMATES
          VELOCITY-VAL
          VELOCITY
          LOCAL_FRIEND-VAL
          LOCAL_FRIEND
          GLOBAL_FRIEND-VAL
          GLOBAL_FRIEND
          LOCAL_BALL-VAL
          LOCAL_BALL
          GLOBAL_BALL-VAL
          GLOBAL_BALL
          LOCAL_BALLS-VAL
          LOCAL_BALLS
          BALLS-VAL
          BALLS
          WAY_POINTS-VAL
          WAY_POINTS
          OBSTACLES-VAL
          OBSTACLES
          OBSTACLE1-VAL
          OBSTACLE1
          OBSTACLE2-VAL
          OBSTACLE2
          KIPER_OBSTACLE-VAL
          KIPER_OBSTACLE
          LOCAL_OBSTACLES-VAL
          LOCAL_OBSTACLES
          GLOBAL_OBSTACLES-VAL
          GLOBAL_OBSTACLES
))