// Generated by gencpp from file fukuro_common/Angle.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_ANGLE_H
#define FUKURO_COMMON_MESSAGE_ANGLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fukuro_common
{
template <class ContainerAllocator>
struct Angle_
{
  typedef Angle_<ContainerAllocator> Type;

  Angle_()
    : theta(0.0)
    , rad(0.0)  {
    }
  Angle_(const ContainerAllocator& _alloc)
    : theta(0.0)
    , rad(0.0)  {
  (void)_alloc;
    }



   typedef double _theta_type;
  _theta_type theta;

   typedef double _rad_type;
  _rad_type rad;





  typedef boost::shared_ptr< ::fukuro_common::Angle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fukuro_common::Angle_<ContainerAllocator> const> ConstPtr;

}; // struct Angle_

typedef ::fukuro_common::Angle_<std::allocator<void> > Angle;

typedef boost::shared_ptr< ::fukuro_common::Angle > AnglePtr;
typedef boost::shared_ptr< ::fukuro_common::Angle const> AngleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fukuro_common::Angle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fukuro_common::Angle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fukuro_common::Angle_<ContainerAllocator1> & lhs, const ::fukuro_common::Angle_<ContainerAllocator2> & rhs)
{
  return lhs.theta == rhs.theta &&
    lhs.rad == rhs.rad;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fukuro_common::Angle_<ContainerAllocator1> & lhs, const ::fukuro_common::Angle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fukuro_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::Angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::Angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::Angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::Angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::Angle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::Angle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fukuro_common::Angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a2f5a7d9a3c91939c8d1626290be18b";
  }

  static const char* value(const ::fukuro_common::Angle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a2f5a7d9a3c9193ULL;
  static const uint64_t static_value2 = 0x9c8d1626290be18bULL;
};

template<class ContainerAllocator>
struct DataType< ::fukuro_common::Angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fukuro_common/Angle";
  }

  static const char* value(const ::fukuro_common::Angle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fukuro_common::Angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 theta\n"
"float64 rad\n"
;
  }

  static const char* value(const ::fukuro_common::Angle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fukuro_common::Angle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.theta);
      stream.next(m.rad);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Angle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fukuro_common::Angle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fukuro_common::Angle_<ContainerAllocator>& v)
  {
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
    s << indent << "rad: ";
    Printer<double>::stream(s, indent + "  ", v.rad);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_ANGLE_H
