// Generated by gencpp from file fukuro_common/CommunicationService.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_COMMUNICATIONSERVICE_H
#define FUKURO_COMMON_MESSAGE_COMMUNICATIONSERVICE_H

#include <ros/service_traits.h>


#include <fukuro_common/CommunicationServiceRequest.h>
#include <fukuro_common/CommunicationServiceResponse.h>


namespace fukuro_common
{

struct CommunicationService
{

typedef CommunicationServiceRequest Request;
typedef CommunicationServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CommunicationService
} // namespace fukuro_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fukuro_common::CommunicationService > {
  static const char* value()
  {
    return "59e80fb04ed5834efebecd78c5beaed9";
  }

  static const char* value(const ::fukuro_common::CommunicationService&) { return value(); }
};

template<>
struct DataType< ::fukuro_common::CommunicationService > {
  static const char* value()
  {
    return "fukuro_common/CommunicationService";
  }

  static const char* value(const ::fukuro_common::CommunicationService&) { return value(); }
};


// service_traits::MD5Sum< ::fukuro_common::CommunicationServiceRequest> should match
// service_traits::MD5Sum< ::fukuro_common::CommunicationService >
template<>
struct MD5Sum< ::fukuro_common::CommunicationServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fukuro_common::CommunicationService >::value();
  }
  static const char* value(const ::fukuro_common::CommunicationServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fukuro_common::CommunicationServiceRequest> should match
// service_traits::DataType< ::fukuro_common::CommunicationService >
template<>
struct DataType< ::fukuro_common::CommunicationServiceRequest>
{
  static const char* value()
  {
    return DataType< ::fukuro_common::CommunicationService >::value();
  }
  static const char* value(const ::fukuro_common::CommunicationServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fukuro_common::CommunicationServiceResponse> should match
// service_traits::MD5Sum< ::fukuro_common::CommunicationService >
template<>
struct MD5Sum< ::fukuro_common::CommunicationServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fukuro_common::CommunicationService >::value();
  }
  static const char* value(const ::fukuro_common::CommunicationServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fukuro_common::CommunicationServiceResponse> should match
// service_traits::DataType< ::fukuro_common::CommunicationService >
template<>
struct DataType< ::fukuro_common::CommunicationServiceResponse>
{
  static const char* value()
  {
    return DataType< ::fukuro_common::CommunicationService >::value();
  }
  static const char* value(const ::fukuro_common::CommunicationServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_COMMUNICATIONSERVICE_H
