// Generated by gencpp from file fukuro_common/CommunicationServiceRequest.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_COMMUNICATIONSERVICEREQUEST_H
#define FUKURO_COMMON_MESSAGE_COMMUNICATIONSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fukuro_common
{
template <class ContainerAllocator>
struct CommunicationServiceRequest_
{
  typedef CommunicationServiceRequest_<ContainerAllocator> Type;

  CommunicationServiceRequest_()
    : connect(0)
    , address()
    , tx_port(0)
    , rx_port(0)  {
    }
  CommunicationServiceRequest_(const ContainerAllocator& _alloc)
    : connect(0)
    , address(_alloc)
    , tx_port(0)
    , rx_port(0)  {
  (void)_alloc;
    }



   typedef uint8_t _connect_type;
  _connect_type connect;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _address_type;
  _address_type address;

   typedef int64_t _tx_port_type;
  _tx_port_type tx_port;

   typedef int64_t _rx_port_type;
  _rx_port_type rx_port;





  typedef boost::shared_ptr< ::fukuro_common::CommunicationServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fukuro_common::CommunicationServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CommunicationServiceRequest_

typedef ::fukuro_common::CommunicationServiceRequest_<std::allocator<void> > CommunicationServiceRequest;

typedef boost::shared_ptr< ::fukuro_common::CommunicationServiceRequest > CommunicationServiceRequestPtr;
typedef boost::shared_ptr< ::fukuro_common::CommunicationServiceRequest const> CommunicationServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fukuro_common::CommunicationServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fukuro_common::CommunicationServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fukuro_common::CommunicationServiceRequest_<ContainerAllocator1> & lhs, const ::fukuro_common::CommunicationServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.connect == rhs.connect &&
    lhs.address == rhs.address &&
    lhs.tx_port == rhs.tx_port &&
    lhs.rx_port == rhs.rx_port;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fukuro_common::CommunicationServiceRequest_<ContainerAllocator1> & lhs, const ::fukuro_common::CommunicationServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fukuro_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::CommunicationServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::CommunicationServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::CommunicationServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::CommunicationServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::CommunicationServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::CommunicationServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fukuro_common::CommunicationServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9850078dcf04bfa18c947ca41a0a993a";
  }

  static const char* value(const ::fukuro_common::CommunicationServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9850078dcf04bfa1ULL;
  static const uint64_t static_value2 = 0x8c947ca41a0a993aULL;
};

template<class ContainerAllocator>
struct DataType< ::fukuro_common::CommunicationServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fukuro_common/CommunicationServiceRequest";
  }

  static const char* value(const ::fukuro_common::CommunicationServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fukuro_common::CommunicationServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 connect\n"
"string address\n"
"int64 tx_port\n"
"int64 rx_port\n"
;
  }

  static const char* value(const ::fukuro_common::CommunicationServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fukuro_common::CommunicationServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.connect);
      stream.next(m.address);
      stream.next(m.tx_port);
      stream.next(m.rx_port);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommunicationServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fukuro_common::CommunicationServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fukuro_common::CommunicationServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "connect: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.connect);
    s << indent << "address: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.address);
    s << indent << "tx_port: ";
    Printer<int64_t>::stream(s, indent + "  ", v.tx_port);
    s << indent << "rx_port: ";
    Printer<int64_t>::stream(s, indent + "  ", v.rx_port);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_COMMUNICATIONSERVICEREQUEST_H
