// Generated by gencpp from file fukuro_common/HWControllerAutotuning.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_HWCONTROLLERAUTOTUNING_H
#define FUKURO_COMMON_MESSAGE_HWCONTROLLERAUTOTUNING_H

#include <ros/service_traits.h>


#include <fukuro_common/HWControllerAutotuningRequest.h>
#include <fukuro_common/HWControllerAutotuningResponse.h>


namespace fukuro_common
{

struct HWControllerAutotuning
{

typedef HWControllerAutotuningRequest Request;
typedef HWControllerAutotuningResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HWControllerAutotuning
} // namespace fukuro_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fukuro_common::HWControllerAutotuning > {
  static const char* value()
  {
    return "0f32fea8c4ca87c8aabb5a11fa7acb8a";
  }

  static const char* value(const ::fukuro_common::HWControllerAutotuning&) { return value(); }
};

template<>
struct DataType< ::fukuro_common::HWControllerAutotuning > {
  static const char* value()
  {
    return "fukuro_common/HWControllerAutotuning";
  }

  static const char* value(const ::fukuro_common::HWControllerAutotuning&) { return value(); }
};


// service_traits::MD5Sum< ::fukuro_common::HWControllerAutotuningRequest> should match
// service_traits::MD5Sum< ::fukuro_common::HWControllerAutotuning >
template<>
struct MD5Sum< ::fukuro_common::HWControllerAutotuningRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fukuro_common::HWControllerAutotuning >::value();
  }
  static const char* value(const ::fukuro_common::HWControllerAutotuningRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fukuro_common::HWControllerAutotuningRequest> should match
// service_traits::DataType< ::fukuro_common::HWControllerAutotuning >
template<>
struct DataType< ::fukuro_common::HWControllerAutotuningRequest>
{
  static const char* value()
  {
    return DataType< ::fukuro_common::HWControllerAutotuning >::value();
  }
  static const char* value(const ::fukuro_common::HWControllerAutotuningRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fukuro_common::HWControllerAutotuningResponse> should match
// service_traits::MD5Sum< ::fukuro_common::HWControllerAutotuning >
template<>
struct MD5Sum< ::fukuro_common::HWControllerAutotuningResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fukuro_common::HWControllerAutotuning >::value();
  }
  static const char* value(const ::fukuro_common::HWControllerAutotuningResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fukuro_common::HWControllerAutotuningResponse> should match
// service_traits::DataType< ::fukuro_common::HWControllerAutotuning >
template<>
struct DataType< ::fukuro_common::HWControllerAutotuningResponse>
{
  static const char* value()
  {
    return DataType< ::fukuro_common::HWControllerAutotuning >::value();
  }
  static const char* value(const ::fukuro_common::HWControllerAutotuningResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_HWCONTROLLERAUTOTUNING_H
