// Generated by gencpp from file fukuro_common/HWControllerParam.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_HWCONTROLLERPARAM_H
#define FUKURO_COMMON_MESSAGE_HWCONTROLLERPARAM_H

#include <ros/service_traits.h>


#include <fukuro_common/HWControllerParamRequest.h>
#include <fukuro_common/HWControllerParamResponse.h>


namespace fukuro_common
{

struct HWControllerParam
{

typedef HWControllerParamRequest Request;
typedef HWControllerParamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HWControllerParam
} // namespace fukuro_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fukuro_common::HWControllerParam > {
  static const char* value()
  {
    return "e54c465f93b763147b0cf60d586ba040";
  }

  static const char* value(const ::fukuro_common::HWControllerParam&) { return value(); }
};

template<>
struct DataType< ::fukuro_common::HWControllerParam > {
  static const char* value()
  {
    return "fukuro_common/HWControllerParam";
  }

  static const char* value(const ::fukuro_common::HWControllerParam&) { return value(); }
};


// service_traits::MD5Sum< ::fukuro_common::HWControllerParamRequest> should match
// service_traits::MD5Sum< ::fukuro_common::HWControllerParam >
template<>
struct MD5Sum< ::fukuro_common::HWControllerParamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fukuro_common::HWControllerParam >::value();
  }
  static const char* value(const ::fukuro_common::HWControllerParamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fukuro_common::HWControllerParamRequest> should match
// service_traits::DataType< ::fukuro_common::HWControllerParam >
template<>
struct DataType< ::fukuro_common::HWControllerParamRequest>
{
  static const char* value()
  {
    return DataType< ::fukuro_common::HWControllerParam >::value();
  }
  static const char* value(const ::fukuro_common::HWControllerParamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fukuro_common::HWControllerParamResponse> should match
// service_traits::MD5Sum< ::fukuro_common::HWControllerParam >
template<>
struct MD5Sum< ::fukuro_common::HWControllerParamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fukuro_common::HWControllerParam >::value();
  }
  static const char* value(const ::fukuro_common::HWControllerParamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fukuro_common::HWControllerParamResponse> should match
// service_traits::DataType< ::fukuro_common::HWControllerParam >
template<>
struct DataType< ::fukuro_common::HWControllerParamResponse>
{
  static const char* value()
  {
    return DataType< ::fukuro_common::HWControllerParam >::value();
  }
  static const char* value(const ::fukuro_common::HWControllerParamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_HWCONTROLLERPARAM_H
