// Generated by gencpp from file fukuro_common/HWControllerManual.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_HWCONTROLLERMANUAL_H
#define FUKURO_COMMON_MESSAGE_HWCONTROLLERMANUAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fukuro_common
{
template <class ContainerAllocator>
struct HWControllerManual_
{
  typedef HWControllerManual_<ContainerAllocator> Type;

  HWControllerManual_()
    : vx(0.0)
    , vy(0.0)
    , w(0.0)  {
    }
  HWControllerManual_(const ContainerAllocator& _alloc)
    : vx(0.0)
    , vy(0.0)
    , w(0.0)  {
  (void)_alloc;
    }



   typedef double _vx_type;
  _vx_type vx;

   typedef double _vy_type;
  _vy_type vy;

   typedef double _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::fukuro_common::HWControllerManual_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fukuro_common::HWControllerManual_<ContainerAllocator> const> ConstPtr;

}; // struct HWControllerManual_

typedef ::fukuro_common::HWControllerManual_<std::allocator<void> > HWControllerManual;

typedef boost::shared_ptr< ::fukuro_common::HWControllerManual > HWControllerManualPtr;
typedef boost::shared_ptr< ::fukuro_common::HWControllerManual const> HWControllerManualConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fukuro_common::HWControllerManual_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fukuro_common::HWControllerManual_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fukuro_common::HWControllerManual_<ContainerAllocator1> & lhs, const ::fukuro_common::HWControllerManual_<ContainerAllocator2> & rhs)
{
  return lhs.vx == rhs.vx &&
    lhs.vy == rhs.vy &&
    lhs.w == rhs.w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fukuro_common::HWControllerManual_<ContainerAllocator1> & lhs, const ::fukuro_common::HWControllerManual_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fukuro_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::HWControllerManual_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::HWControllerManual_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::HWControllerManual_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::HWControllerManual_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::HWControllerManual_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::HWControllerManual_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fukuro_common::HWControllerManual_<ContainerAllocator> >
{
  static const char* value()
  {
    return "461e74593b26c77a7c97f00fe82c6d79";
  }

  static const char* value(const ::fukuro_common::HWControllerManual_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x461e74593b26c77aULL;
  static const uint64_t static_value2 = 0x7c97f00fe82c6d79ULL;
};

template<class ContainerAllocator>
struct DataType< ::fukuro_common::HWControllerManual_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fukuro_common/HWControllerManual";
  }

  static const char* value(const ::fukuro_common::HWControllerManual_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fukuro_common::HWControllerManual_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 vx\n"
"float64 vy\n"
"float64 w\n"
;
  }

  static const char* value(const ::fukuro_common::HWControllerManual_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fukuro_common::HWControllerManual_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HWControllerManual_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fukuro_common::HWControllerManual_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fukuro_common::HWControllerManual_<ContainerAllocator>& v)
  {
    s << indent << "vx: ";
    Printer<double>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<double>::stream(s, indent + "  ", v.vy);
    s << indent << "w: ";
    Printer<double>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_HWCONTROLLERMANUAL_H
