// Generated by gencpp from file fukuro_common/HWController.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_HWCONTROLLER_H
#define FUKURO_COMMON_MESSAGE_HWCONTROLLER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <fukuro_common/Encoder.h>
#include <fukuro_common/Encoder.h>
#include <fukuro_common/PWM.h>
#include <fukuro_common/Compass.h>
#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/Pose2D.h>

namespace fukuro_common
{
template <class ContainerAllocator>
struct HWController_
{
  typedef HWController_<ContainerAllocator> Type;

  HWController_()
    : encoder()
    , freewheel()
    , pwm()
    , compass()
    , ir(0)
    , vel()
    , vel_cmd()  {
    }
  HWController_(const ContainerAllocator& _alloc)
    : encoder(_alloc)
    , freewheel(_alloc)
    , pwm(_alloc)
    , compass(_alloc)
    , ir(0)
    , vel(_alloc)
    , vel_cmd(_alloc)  {
  (void)_alloc;
    }



   typedef  ::fukuro_common::Encoder_<ContainerAllocator>  _encoder_type;
  _encoder_type encoder;

   typedef  ::fukuro_common::Encoder_<ContainerAllocator>  _freewheel_type;
  _freewheel_type freewheel;

   typedef  ::fukuro_common::PWM_<ContainerAllocator>  _pwm_type;
  _pwm_type pwm;

   typedef  ::fukuro_common::Compass_<ContainerAllocator>  _compass_type;
  _compass_type compass;

   typedef int8_t _ir_type;
  _ir_type ir;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _vel_type;
  _vel_type vel;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _vel_cmd_type;
  _vel_cmd_type vel_cmd;





  typedef boost::shared_ptr< ::fukuro_common::HWController_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fukuro_common::HWController_<ContainerAllocator> const> ConstPtr;

}; // struct HWController_

typedef ::fukuro_common::HWController_<std::allocator<void> > HWController;

typedef boost::shared_ptr< ::fukuro_common::HWController > HWControllerPtr;
typedef boost::shared_ptr< ::fukuro_common::HWController const> HWControllerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fukuro_common::HWController_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fukuro_common::HWController_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fukuro_common::HWController_<ContainerAllocator1> & lhs, const ::fukuro_common::HWController_<ContainerAllocator2> & rhs)
{
  return lhs.encoder == rhs.encoder &&
    lhs.freewheel == rhs.freewheel &&
    lhs.pwm == rhs.pwm &&
    lhs.compass == rhs.compass &&
    lhs.ir == rhs.ir &&
    lhs.vel == rhs.vel &&
    lhs.vel_cmd == rhs.vel_cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fukuro_common::HWController_<ContainerAllocator1> & lhs, const ::fukuro_common::HWController_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fukuro_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::HWController_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::HWController_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::HWController_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::HWController_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::HWController_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::HWController_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fukuro_common::HWController_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5b17edd995ef9a46dfd3ca5601a27eaf";
  }

  static const char* value(const ::fukuro_common::HWController_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5b17edd995ef9a46ULL;
  static const uint64_t static_value2 = 0xdfd3ca5601a27eafULL;
};

template<class ContainerAllocator>
struct DataType< ::fukuro_common::HWController_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fukuro_common/HWController";
  }

  static const char* value(const ::fukuro_common::HWController_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fukuro_common::HWController_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Encoder encoder\n"
"Encoder freewheel\n"
"PWM pwm\n"
"Compass compass\n"
"int8 ir\n"
"geometry_msgs/Pose2D vel\n"
"geometry_msgs/Pose2D vel_cmd\n"
"================================================================================\n"
"MSG: fukuro_common/Encoder\n"
"int32 m1\n"
"int32 m2\n"
"int32 m3\n"
"================================================================================\n"
"MSG: fukuro_common/PWM\n"
"float64 m1\n"
"float64 m2\n"
"float64 m3\n"
"================================================================================\n"
"MSG: fukuro_common/Compass\n"
"float64 cmps\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::fukuro_common::HWController_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fukuro_common::HWController_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.encoder);
      stream.next(m.freewheel);
      stream.next(m.pwm);
      stream.next(m.compass);
      stream.next(m.ir);
      stream.next(m.vel);
      stream.next(m.vel_cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HWController_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fukuro_common::HWController_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fukuro_common::HWController_<ContainerAllocator>& v)
  {
    s << indent << "encoder: ";
    s << std::endl;
    Printer< ::fukuro_common::Encoder_<ContainerAllocator> >::stream(s, indent + "  ", v.encoder);
    s << indent << "freewheel: ";
    s << std::endl;
    Printer< ::fukuro_common::Encoder_<ContainerAllocator> >::stream(s, indent + "  ", v.freewheel);
    s << indent << "pwm: ";
    s << std::endl;
    Printer< ::fukuro_common::PWM_<ContainerAllocator> >::stream(s, indent + "  ", v.pwm);
    s << indent << "compass: ";
    s << std::endl;
    Printer< ::fukuro_common::Compass_<ContainerAllocator> >::stream(s, indent + "  ", v.compass);
    s << indent << "ir: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ir);
    s << indent << "vel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.vel);
    s << indent << "vel_cmd: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.vel_cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_HWCONTROLLER_H
