// Generated by gencpp from file fukuro_common/HWControllerPIParam.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_HWCONTROLLERPIPARAM_H
#define FUKURO_COMMON_MESSAGE_HWCONTROLLERPIPARAM_H

#include <ros/service_traits.h>


#include <fukuro_common/HWControllerPIParamRequest.h>
#include <fukuro_common/HWControllerPIParamResponse.h>


namespace fukuro_common
{

struct HWControllerPIParam
{

typedef HWControllerPIParamRequest Request;
typedef HWControllerPIParamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HWControllerPIParam
} // namespace fukuro_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fukuro_common::HWControllerPIParam > {
  static const char* value()
  {
    return "ebbd950a01132723798b799989122afe";
  }

  static const char* value(const ::fukuro_common::HWControllerPIParam&) { return value(); }
};

template<>
struct DataType< ::fukuro_common::HWControllerPIParam > {
  static const char* value()
  {
    return "fukuro_common/HWControllerPIParam";
  }

  static const char* value(const ::fukuro_common::HWControllerPIParam&) { return value(); }
};


// service_traits::MD5Sum< ::fukuro_common::HWControllerPIParamRequest> should match
// service_traits::MD5Sum< ::fukuro_common::HWControllerPIParam >
template<>
struct MD5Sum< ::fukuro_common::HWControllerPIParamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fukuro_common::HWControllerPIParam >::value();
  }
  static const char* value(const ::fukuro_common::HWControllerPIParamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fukuro_common::HWControllerPIParamRequest> should match
// service_traits::DataType< ::fukuro_common::HWControllerPIParam >
template<>
struct DataType< ::fukuro_common::HWControllerPIParamRequest>
{
  static const char* value()
  {
    return DataType< ::fukuro_common::HWControllerPIParam >::value();
  }
  static const char* value(const ::fukuro_common::HWControllerPIParamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fukuro_common::HWControllerPIParamResponse> should match
// service_traits::MD5Sum< ::fukuro_common::HWControllerPIParam >
template<>
struct MD5Sum< ::fukuro_common::HWControllerPIParamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fukuro_common::HWControllerPIParam >::value();
  }
  static const char* value(const ::fukuro_common::HWControllerPIParamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fukuro_common::HWControllerPIParamResponse> should match
// service_traits::DataType< ::fukuro_common::HWControllerPIParam >
template<>
struct DataType< ::fukuro_common::HWControllerPIParamResponse>
{
  static const char* value()
  {
    return DataType< ::fukuro_common::HWControllerPIParam >::value();
  }
  static const char* value(const ::fukuro_common::HWControllerPIParamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_HWCONTROLLERPIPARAM_H
