// Generated by gencpp from file fukuro_common/HWControllerSrv.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_HWCONTROLLERSRV_H
#define FUKURO_COMMON_MESSAGE_HWCONTROLLERSRV_H

#include <ros/service_traits.h>


#include <fukuro_common/HWControllerSrvRequest.h>
#include <fukuro_common/HWControllerSrvResponse.h>


namespace fukuro_common
{

struct HWControllerSrv
{

typedef HWControllerSrvRequest Request;
typedef HWControllerSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HWControllerSrv
} // namespace fukuro_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fukuro_common::HWControllerSrv > {
  static const char* value()
  {
    return "3d5c94862d83cd0042f79f7755128b97";
  }

  static const char* value(const ::fukuro_common::HWControllerSrv&) { return value(); }
};

template<>
struct DataType< ::fukuro_common::HWControllerSrv > {
  static const char* value()
  {
    return "fukuro_common/HWControllerSrv";
  }

  static const char* value(const ::fukuro_common::HWControllerSrv&) { return value(); }
};


// service_traits::MD5Sum< ::fukuro_common::HWControllerSrvRequest> should match
// service_traits::MD5Sum< ::fukuro_common::HWControllerSrv >
template<>
struct MD5Sum< ::fukuro_common::HWControllerSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fukuro_common::HWControllerSrv >::value();
  }
  static const char* value(const ::fukuro_common::HWControllerSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fukuro_common::HWControllerSrvRequest> should match
// service_traits::DataType< ::fukuro_common::HWControllerSrv >
template<>
struct DataType< ::fukuro_common::HWControllerSrvRequest>
{
  static const char* value()
  {
    return DataType< ::fukuro_common::HWControllerSrv >::value();
  }
  static const char* value(const ::fukuro_common::HWControllerSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fukuro_common::HWControllerSrvResponse> should match
// service_traits::MD5Sum< ::fukuro_common::HWControllerSrv >
template<>
struct MD5Sum< ::fukuro_common::HWControllerSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fukuro_common::HWControllerSrv >::value();
  }
  static const char* value(const ::fukuro_common::HWControllerSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fukuro_common::HWControllerSrvResponse> should match
// service_traits::DataType< ::fukuro_common::HWControllerSrv >
template<>
struct DataType< ::fukuro_common::HWControllerSrvResponse>
{
  static const char* value()
  {
    return DataType< ::fukuro_common::HWControllerSrv >::value();
  }
  static const char* value(const ::fukuro_common::HWControllerSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_HWCONTROLLERSRV_H
