// Generated by gencpp from file fukuro_common/HWControllerPIParamResponse.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_HWCONTROLLERPIPARAMRESPONSE_H
#define FUKURO_COMMON_MESSAGE_HWCONTROLLERPIPARAMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fukuro_common
{
template <class ContainerAllocator>
struct HWControllerPIParamResponse_
{
  typedef HWControllerPIParamResponse_<ContainerAllocator> Type;

  HWControllerPIParamResponse_()
    : ok(false)  {
    }
  HWControllerPIParamResponse_(const ContainerAllocator& _alloc)
    : ok(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ok_type;
  _ok_type ok;





  typedef boost::shared_ptr< ::fukuro_common::HWControllerPIParamResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fukuro_common::HWControllerPIParamResponse_<ContainerAllocator> const> ConstPtr;

}; // struct HWControllerPIParamResponse_

typedef ::fukuro_common::HWControllerPIParamResponse_<std::allocator<void> > HWControllerPIParamResponse;

typedef boost::shared_ptr< ::fukuro_common::HWControllerPIParamResponse > HWControllerPIParamResponsePtr;
typedef boost::shared_ptr< ::fukuro_common::HWControllerPIParamResponse const> HWControllerPIParamResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fukuro_common::HWControllerPIParamResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fukuro_common::HWControllerPIParamResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fukuro_common::HWControllerPIParamResponse_<ContainerAllocator1> & lhs, const ::fukuro_common::HWControllerPIParamResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ok == rhs.ok;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fukuro_common::HWControllerPIParamResponse_<ContainerAllocator1> & lhs, const ::fukuro_common::HWControllerPIParamResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fukuro_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::HWControllerPIParamResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::HWControllerPIParamResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::HWControllerPIParamResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::HWControllerPIParamResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::HWControllerPIParamResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::HWControllerPIParamResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fukuro_common::HWControllerPIParamResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f6da3883749771fac40d6deb24a8c02";
  }

  static const char* value(const ::fukuro_common::HWControllerPIParamResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f6da3883749771fULL;
  static const uint64_t static_value2 = 0xac40d6deb24a8c02ULL;
};

template<class ContainerAllocator>
struct DataType< ::fukuro_common::HWControllerPIParamResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fukuro_common/HWControllerPIParamResponse";
  }

  static const char* value(const ::fukuro_common::HWControllerPIParamResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fukuro_common::HWControllerPIParamResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ok\n"
;
  }

  static const char* value(const ::fukuro_common::HWControllerPIParamResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fukuro_common::HWControllerPIParamResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HWControllerPIParamResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fukuro_common::HWControllerPIParamResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fukuro_common::HWControllerPIParamResponse_<ContainerAllocator>& v)
  {
    s << indent << "ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_HWCONTROLLERPIPARAMRESPONSE_H
