// Generated by gencpp from file fukuro_common/Localization.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_LOCALIZATION_H
#define FUKURO_COMMON_MESSAGE_LOCALIZATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/Pose2D.h>

namespace fukuro_common
{
template <class ContainerAllocator>
struct Localization_
{
  typedef Localization_<ContainerAllocator> Type;

  Localization_()
    : estimate_pos()
    , estimate_pos_descrete()
    , particles()
    , best_estimation()
    , weights()
    , best_estimation_weight(0.0)
    , grid_size(0)  {
    }
  Localization_(const ContainerAllocator& _alloc)
    : estimate_pos(_alloc)
    , estimate_pos_descrete(_alloc)
    , particles(_alloc)
    , best_estimation(_alloc)
    , weights(_alloc)
    , best_estimation_weight(0.0)
    , grid_size(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _estimate_pos_type;
  _estimate_pos_type estimate_pos;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _estimate_pos_descrete_type;
  _estimate_pos_descrete_type estimate_pos_descrete;

   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose2D_<ContainerAllocator> >::other >  _particles_type;
  _particles_type particles;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _best_estimation_type;
  _best_estimation_type best_estimation;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _weights_type;
  _weights_type weights;

   typedef double _best_estimation_weight_type;
  _best_estimation_weight_type best_estimation_weight;

   typedef int32_t _grid_size_type;
  _grid_size_type grid_size;





  typedef boost::shared_ptr< ::fukuro_common::Localization_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fukuro_common::Localization_<ContainerAllocator> const> ConstPtr;

}; // struct Localization_

typedef ::fukuro_common::Localization_<std::allocator<void> > Localization;

typedef boost::shared_ptr< ::fukuro_common::Localization > LocalizationPtr;
typedef boost::shared_ptr< ::fukuro_common::Localization const> LocalizationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fukuro_common::Localization_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fukuro_common::Localization_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fukuro_common::Localization_<ContainerAllocator1> & lhs, const ::fukuro_common::Localization_<ContainerAllocator2> & rhs)
{
  return lhs.estimate_pos == rhs.estimate_pos &&
    lhs.estimate_pos_descrete == rhs.estimate_pos_descrete &&
    lhs.particles == rhs.particles &&
    lhs.best_estimation == rhs.best_estimation &&
    lhs.weights == rhs.weights &&
    lhs.best_estimation_weight == rhs.best_estimation_weight &&
    lhs.grid_size == rhs.grid_size;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fukuro_common::Localization_<ContainerAllocator1> & lhs, const ::fukuro_common::Localization_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fukuro_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::Localization_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::Localization_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::Localization_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::Localization_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::Localization_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::Localization_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fukuro_common::Localization_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d25fba6248365fe1c093e492c489b9fd";
  }

  static const char* value(const ::fukuro_common::Localization_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd25fba6248365fe1ULL;
  static const uint64_t static_value2 = 0xc093e492c489b9fdULL;
};

template<class ContainerAllocator>
struct DataType< ::fukuro_common::Localization_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fukuro_common/Localization";
  }

  static const char* value(const ::fukuro_common::Localization_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fukuro_common::Localization_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose2D estimate_pos\n"
"geometry_msgs/Pose2D estimate_pos_descrete\n"
"geometry_msgs/Pose2D[] particles\n"
"geometry_msgs/Pose2D best_estimation\n"
"float64[] weights\n"
"float64 best_estimation_weight\n"
"int32 grid_size\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::fukuro_common::Localization_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fukuro_common::Localization_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.estimate_pos);
      stream.next(m.estimate_pos_descrete);
      stream.next(m.particles);
      stream.next(m.best_estimation);
      stream.next(m.weights);
      stream.next(m.best_estimation_weight);
      stream.next(m.grid_size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Localization_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fukuro_common::Localization_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fukuro_common::Localization_<ContainerAllocator>& v)
  {
    s << indent << "estimate_pos: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.estimate_pos);
    s << indent << "estimate_pos_descrete: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.estimate_pos_descrete);
    s << indent << "particles[]" << std::endl;
    for (size_t i = 0; i < v.particles.size(); ++i)
    {
      s << indent << "  particles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.particles[i]);
    }
    s << indent << "best_estimation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.best_estimation);
    s << indent << "weights[]" << std::endl;
    for (size_t i = 0; i < v.weights.size(); ++i)
    {
      s << indent << "  weights[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.weights[i]);
    }
    s << indent << "best_estimation_weight: ";
    Printer<double>::stream(s, indent + "  ", v.best_estimation_weight);
    s << indent << "grid_size: ";
    Printer<int32_t>::stream(s, indent + "  ", v.grid_size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_LOCALIZATION_H
