// Generated by gencpp from file fukuro_common/LocalizationSrv.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_LOCALIZATIONSRV_H
#define FUKURO_COMMON_MESSAGE_LOCALIZATIONSRV_H

#include <ros/service_traits.h>


#include <fukuro_common/LocalizationSrvRequest.h>
#include <fukuro_common/LocalizationSrvResponse.h>


namespace fukuro_common
{

struct LocalizationSrv
{

typedef LocalizationSrvRequest Request;
typedef LocalizationSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LocalizationSrv
} // namespace fukuro_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fukuro_common::LocalizationSrv > {
  static const char* value()
  {
    return "3e656325d982b6bf93fe099b9e93f49c";
  }

  static const char* value(const ::fukuro_common::LocalizationSrv&) { return value(); }
};

template<>
struct DataType< ::fukuro_common::LocalizationSrv > {
  static const char* value()
  {
    return "fukuro_common/LocalizationSrv";
  }

  static const char* value(const ::fukuro_common::LocalizationSrv&) { return value(); }
};


// service_traits::MD5Sum< ::fukuro_common::LocalizationSrvRequest> should match
// service_traits::MD5Sum< ::fukuro_common::LocalizationSrv >
template<>
struct MD5Sum< ::fukuro_common::LocalizationSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fukuro_common::LocalizationSrv >::value();
  }
  static const char* value(const ::fukuro_common::LocalizationSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fukuro_common::LocalizationSrvRequest> should match
// service_traits::DataType< ::fukuro_common::LocalizationSrv >
template<>
struct DataType< ::fukuro_common::LocalizationSrvRequest>
{
  static const char* value()
  {
    return DataType< ::fukuro_common::LocalizationSrv >::value();
  }
  static const char* value(const ::fukuro_common::LocalizationSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fukuro_common::LocalizationSrvResponse> should match
// service_traits::MD5Sum< ::fukuro_common::LocalizationSrv >
template<>
struct MD5Sum< ::fukuro_common::LocalizationSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fukuro_common::LocalizationSrv >::value();
  }
  static const char* value(const ::fukuro_common::LocalizationSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fukuro_common::LocalizationSrvResponse> should match
// service_traits::DataType< ::fukuro_common::LocalizationSrv >
template<>
struct DataType< ::fukuro_common::LocalizationSrvResponse>
{
  static const char* value()
  {
    return DataType< ::fukuro_common::LocalizationSrv >::value();
  }
  static const char* value(const ::fukuro_common::LocalizationSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_LOCALIZATIONSRV_H
