// Generated by gencpp from file fukuro_common/MotorVel.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_MOTORVEL_H
#define FUKURO_COMMON_MESSAGE_MOTORVEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fukuro_common
{
template <class ContainerAllocator>
struct MotorVel_
{
  typedef MotorVel_<ContainerAllocator> Type;

  MotorVel_()
    : m1(0.0)
    , m2(0.0)
    , m3(0.0)  {
    }
  MotorVel_(const ContainerAllocator& _alloc)
    : m1(0.0)
    , m2(0.0)
    , m3(0.0)  {
  (void)_alloc;
    }



   typedef float _m1_type;
  _m1_type m1;

   typedef float _m2_type;
  _m2_type m2;

   typedef float _m3_type;
  _m3_type m3;





  typedef boost::shared_ptr< ::fukuro_common::MotorVel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fukuro_common::MotorVel_<ContainerAllocator> const> ConstPtr;

}; // struct MotorVel_

typedef ::fukuro_common::MotorVel_<std::allocator<void> > MotorVel;

typedef boost::shared_ptr< ::fukuro_common::MotorVel > MotorVelPtr;
typedef boost::shared_ptr< ::fukuro_common::MotorVel const> MotorVelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fukuro_common::MotorVel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fukuro_common::MotorVel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fukuro_common::MotorVel_<ContainerAllocator1> & lhs, const ::fukuro_common::MotorVel_<ContainerAllocator2> & rhs)
{
  return lhs.m1 == rhs.m1 &&
    lhs.m2 == rhs.m2 &&
    lhs.m3 == rhs.m3;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fukuro_common::MotorVel_<ContainerAllocator1> & lhs, const ::fukuro_common::MotorVel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fukuro_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::MotorVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::MotorVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::MotorVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::MotorVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::MotorVel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::MotorVel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fukuro_common::MotorVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a86e25d23be69cefa1d2e044fba11b0c";
  }

  static const char* value(const ::fukuro_common::MotorVel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa86e25d23be69cefULL;
  static const uint64_t static_value2 = 0xa1d2e044fba11b0cULL;
};

template<class ContainerAllocator>
struct DataType< ::fukuro_common::MotorVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fukuro_common/MotorVel";
  }

  static const char* value(const ::fukuro_common::MotorVel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fukuro_common::MotorVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 m1\n"
"float32 m2\n"
"float32 m3\n"
;
  }

  static const char* value(const ::fukuro_common::MotorVel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fukuro_common::MotorVel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.m1);
      stream.next(m.m2);
      stream.next(m.m3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorVel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fukuro_common::MotorVel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fukuro_common::MotorVel_<ContainerAllocator>& v)
  {
    s << indent << "m1: ";
    Printer<float>::stream(s, indent + "  ", v.m1);
    s << indent << "m2: ";
    Printer<float>::stream(s, indent + "  ", v.m2);
    s << indent << "m3: ";
    Printer<float>::stream(s, indent + "  ", v.m3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_MOTORVEL_H
