// Generated by gencpp from file fukuro_common/Obstacles.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_OBSTACLES_H
#define FUKURO_COMMON_MESSAGE_OBSTACLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <fukuro_common/Obstacle.h>

namespace fukuro_common
{
template <class ContainerAllocator>
struct Obstacles_
{
  typedef Obstacles_<ContainerAllocator> Type;

  Obstacles_()
    : obs()  {
    }
  Obstacles_(const ContainerAllocator& _alloc)
    : obs(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::fukuro_common::Obstacle_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::fukuro_common::Obstacle_<ContainerAllocator> >::other >  _obs_type;
  _obs_type obs;





  typedef boost::shared_ptr< ::fukuro_common::Obstacles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fukuro_common::Obstacles_<ContainerAllocator> const> ConstPtr;

}; // struct Obstacles_

typedef ::fukuro_common::Obstacles_<std::allocator<void> > Obstacles;

typedef boost::shared_ptr< ::fukuro_common::Obstacles > ObstaclesPtr;
typedef boost::shared_ptr< ::fukuro_common::Obstacles const> ObstaclesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fukuro_common::Obstacles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fukuro_common::Obstacles_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fukuro_common::Obstacles_<ContainerAllocator1> & lhs, const ::fukuro_common::Obstacles_<ContainerAllocator2> & rhs)
{
  return lhs.obs == rhs.obs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fukuro_common::Obstacles_<ContainerAllocator1> & lhs, const ::fukuro_common::Obstacles_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fukuro_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::Obstacles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::Obstacles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::Obstacles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::Obstacles_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::Obstacles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::Obstacles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fukuro_common::Obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a9d0234d57573448b583f3223c799a5";
  }

  static const char* value(const ::fukuro_common::Obstacles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a9d0234d5757344ULL;
  static const uint64_t static_value2 = 0x8b583f3223c799a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::fukuro_common::Obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fukuro_common/Obstacles";
  }

  static const char* value(const ::fukuro_common::Obstacles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fukuro_common::Obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Obstacle[] obs\n"
"================================================================================\n"
"MSG: fukuro_common/Obstacle\n"
"Point2d pos\n"
"float64 r\n"
"int8 shape\n"
"================================================================================\n"
"MSG: fukuro_common/Point2d\n"
"float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::fukuro_common::Obstacles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fukuro_common::Obstacles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Obstacles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fukuro_common::Obstacles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fukuro_common::Obstacles_<ContainerAllocator>& v)
  {
    s << indent << "obs[]" << std::endl;
    for (size_t i = 0; i < v.obs.size(); ++i)
    {
      s << indent << "  obs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::fukuro_common::Obstacle_<ContainerAllocator> >::stream(s, indent + "    ", v.obs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_OBSTACLES_H
