// Generated by gencpp from file fukuro_common/ObstaclesService.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_OBSTACLESSERVICE_H
#define FUKURO_COMMON_MESSAGE_OBSTACLESSERVICE_H

#include <ros/service_traits.h>


#include <fukuro_common/ObstaclesServiceRequest.h>
#include <fukuro_common/ObstaclesServiceResponse.h>


namespace fukuro_common
{

struct ObstaclesService
{

typedef ObstaclesServiceRequest Request;
typedef ObstaclesServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ObstaclesService
} // namespace fukuro_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fukuro_common::ObstaclesService > {
  static const char* value()
  {
    return "81a6d1748dadd1a2f252dedfae401a7d";
  }

  static const char* value(const ::fukuro_common::ObstaclesService&) { return value(); }
};

template<>
struct DataType< ::fukuro_common::ObstaclesService > {
  static const char* value()
  {
    return "fukuro_common/ObstaclesService";
  }

  static const char* value(const ::fukuro_common::ObstaclesService&) { return value(); }
};


// service_traits::MD5Sum< ::fukuro_common::ObstaclesServiceRequest> should match
// service_traits::MD5Sum< ::fukuro_common::ObstaclesService >
template<>
struct MD5Sum< ::fukuro_common::ObstaclesServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fukuro_common::ObstaclesService >::value();
  }
  static const char* value(const ::fukuro_common::ObstaclesServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fukuro_common::ObstaclesServiceRequest> should match
// service_traits::DataType< ::fukuro_common::ObstaclesService >
template<>
struct DataType< ::fukuro_common::ObstaclesServiceRequest>
{
  static const char* value()
  {
    return DataType< ::fukuro_common::ObstaclesService >::value();
  }
  static const char* value(const ::fukuro_common::ObstaclesServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fukuro_common::ObstaclesServiceResponse> should match
// service_traits::MD5Sum< ::fukuro_common::ObstaclesService >
template<>
struct MD5Sum< ::fukuro_common::ObstaclesServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fukuro_common::ObstaclesService >::value();
  }
  static const char* value(const ::fukuro_common::ObstaclesServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fukuro_common::ObstaclesServiceResponse> should match
// service_traits::DataType< ::fukuro_common::ObstaclesService >
template<>
struct DataType< ::fukuro_common::ObstaclesServiceResponse>
{
  static const char* value()
  {
    return DataType< ::fukuro_common::ObstaclesService >::value();
  }
  static const char* value(const ::fukuro_common::ObstaclesServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_OBSTACLESSERVICE_H
