// Generated by gencpp from file fukuro_common/OdometryService.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_ODOMETRYSERVICE_H
#define FUKURO_COMMON_MESSAGE_ODOMETRYSERVICE_H

#include <ros/service_traits.h>


#include <fukuro_common/OdometryServiceRequest.h>
#include <fukuro_common/OdometryServiceResponse.h>


namespace fukuro_common
{

struct OdometryService
{

typedef OdometryServiceRequest Request;
typedef OdometryServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OdometryService
} // namespace fukuro_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fukuro_common::OdometryService > {
  static const char* value()
  {
    return "53452fdf3dd1b1dec99dc1c69895e9cf";
  }

  static const char* value(const ::fukuro_common::OdometryService&) { return value(); }
};

template<>
struct DataType< ::fukuro_common::OdometryService > {
  static const char* value()
  {
    return "fukuro_common/OdometryService";
  }

  static const char* value(const ::fukuro_common::OdometryService&) { return value(); }
};


// service_traits::MD5Sum< ::fukuro_common::OdometryServiceRequest> should match
// service_traits::MD5Sum< ::fukuro_common::OdometryService >
template<>
struct MD5Sum< ::fukuro_common::OdometryServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fukuro_common::OdometryService >::value();
  }
  static const char* value(const ::fukuro_common::OdometryServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fukuro_common::OdometryServiceRequest> should match
// service_traits::DataType< ::fukuro_common::OdometryService >
template<>
struct DataType< ::fukuro_common::OdometryServiceRequest>
{
  static const char* value()
  {
    return DataType< ::fukuro_common::OdometryService >::value();
  }
  static const char* value(const ::fukuro_common::OdometryServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fukuro_common::OdometryServiceResponse> should match
// service_traits::MD5Sum< ::fukuro_common::OdometryService >
template<>
struct MD5Sum< ::fukuro_common::OdometryServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fukuro_common::OdometryService >::value();
  }
  static const char* value(const ::fukuro_common::OdometryServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fukuro_common::OdometryServiceResponse> should match
// service_traits::DataType< ::fukuro_common::OdometryService >
template<>
struct DataType< ::fukuro_common::OdometryServiceResponse>
{
  static const char* value()
  {
    return DataType< ::fukuro_common::OdometryService >::value();
  }
  static const char* value(const ::fukuro_common::OdometryServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_ODOMETRYSERVICE_H
