// Generated by gencpp from file fukuro_common/OdometryInfo.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_ODOMETRYINFO_H
#define FUKURO_COMMON_MESSAGE_ODOMETRYINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/Pose2D.h>

namespace fukuro_common
{
template <class ContainerAllocator>
struct OdometryInfo_
{
  typedef OdometryInfo_<ContainerAllocator> Type;

  OdometryInfo_()
    : vx(0.0)
    , vy(0.0)
    , w(0.0)
    , position()
    , velocity()  {
    }
  OdometryInfo_(const ContainerAllocator& _alloc)
    : vx(0.0)
    , vy(0.0)
    , w(0.0)
    , position(_alloc)
    , velocity(_alloc)  {
  (void)_alloc;
    }



   typedef double _vx_type;
  _vx_type vx;

   typedef double _vy_type;
  _vy_type vy;

   typedef double _w_type;
  _w_type w;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::fukuro_common::OdometryInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fukuro_common::OdometryInfo_<ContainerAllocator> const> ConstPtr;

}; // struct OdometryInfo_

typedef ::fukuro_common::OdometryInfo_<std::allocator<void> > OdometryInfo;

typedef boost::shared_ptr< ::fukuro_common::OdometryInfo > OdometryInfoPtr;
typedef boost::shared_ptr< ::fukuro_common::OdometryInfo const> OdometryInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fukuro_common::OdometryInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fukuro_common::OdometryInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fukuro_common::OdometryInfo_<ContainerAllocator1> & lhs, const ::fukuro_common::OdometryInfo_<ContainerAllocator2> & rhs)
{
  return lhs.vx == rhs.vx &&
    lhs.vy == rhs.vy &&
    lhs.w == rhs.w &&
    lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fukuro_common::OdometryInfo_<ContainerAllocator1> & lhs, const ::fukuro_common::OdometryInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fukuro_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::OdometryInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::OdometryInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::OdometryInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::OdometryInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::OdometryInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::OdometryInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fukuro_common::OdometryInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba676638abfd6dd3d3cce86d90468aab";
  }

  static const char* value(const ::fukuro_common::OdometryInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba676638abfd6dd3ULL;
  static const uint64_t static_value2 = 0xd3cce86d90468aabULL;
};

template<class ContainerAllocator>
struct DataType< ::fukuro_common::OdometryInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fukuro_common/OdometryInfo";
  }

  static const char* value(const ::fukuro_common::OdometryInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fukuro_common::OdometryInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 vx\n"
"float64 vy\n"
"float64 w\n"
"geometry_msgs/Pose2D position\n"
"geometry_msgs/Pose2D velocity\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::fukuro_common::OdometryInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fukuro_common::OdometryInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.w);
      stream.next(m.position);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OdometryInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fukuro_common::OdometryInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fukuro_common::OdometryInfo_<ContainerAllocator>& v)
  {
    s << indent << "vx: ";
    Printer<double>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<double>::stream(s, indent + "  ", v.vy);
    s << indent << "w: ";
    Printer<double>::stream(s, indent + "  ", v.w);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_ODOMETRYINFO_H
