// Generated by gencpp from file fukuro_common/OdometryCalibration.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_ODOMETRYCALIBRATION_H
#define FUKURO_COMMON_MESSAGE_ODOMETRYCALIBRATION_H

#include <ros/service_traits.h>


#include <fukuro_common/OdometryCalibrationRequest.h>
#include <fukuro_common/OdometryCalibrationResponse.h>


namespace fukuro_common
{

struct OdometryCalibration
{

typedef OdometryCalibrationRequest Request;
typedef OdometryCalibrationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OdometryCalibration
} // namespace fukuro_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fukuro_common::OdometryCalibration > {
  static const char* value()
  {
    return "ebc612ce0a9b4b65aa74121fecb4e9f3";
  }

  static const char* value(const ::fukuro_common::OdometryCalibration&) { return value(); }
};

template<>
struct DataType< ::fukuro_common::OdometryCalibration > {
  static const char* value()
  {
    return "fukuro_common/OdometryCalibration";
  }

  static const char* value(const ::fukuro_common::OdometryCalibration&) { return value(); }
};


// service_traits::MD5Sum< ::fukuro_common::OdometryCalibrationRequest> should match
// service_traits::MD5Sum< ::fukuro_common::OdometryCalibration >
template<>
struct MD5Sum< ::fukuro_common::OdometryCalibrationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fukuro_common::OdometryCalibration >::value();
  }
  static const char* value(const ::fukuro_common::OdometryCalibrationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fukuro_common::OdometryCalibrationRequest> should match
// service_traits::DataType< ::fukuro_common::OdometryCalibration >
template<>
struct DataType< ::fukuro_common::OdometryCalibrationRequest>
{
  static const char* value()
  {
    return DataType< ::fukuro_common::OdometryCalibration >::value();
  }
  static const char* value(const ::fukuro_common::OdometryCalibrationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fukuro_common::OdometryCalibrationResponse> should match
// service_traits::MD5Sum< ::fukuro_common::OdometryCalibration >
template<>
struct MD5Sum< ::fukuro_common::OdometryCalibrationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fukuro_common::OdometryCalibration >::value();
  }
  static const char* value(const ::fukuro_common::OdometryCalibrationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fukuro_common::OdometryCalibrationResponse> should match
// service_traits::DataType< ::fukuro_common::OdometryCalibration >
template<>
struct DataType< ::fukuro_common::OdometryCalibrationResponse>
{
  static const char* value()
  {
    return DataType< ::fukuro_common::OdometryCalibration >::value();
  }
  static const char* value(const ::fukuro_common::OdometryCalibrationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_ODOMETRYCALIBRATION_H
