// Generated by gencpp from file fukuro_common/OdometryServiceResponse.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_ODOMETRYSERVICERESPONSE_H
#define FUKURO_COMMON_MESSAGE_ODOMETRYSERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fukuro_common
{
template <class ContainerAllocator>
struct OdometryServiceResponse_
{
  typedef OdometryServiceResponse_<ContainerAllocator> Type;

  OdometryServiceResponse_()
    : ok(0)  {
    }
  OdometryServiceResponse_(const ContainerAllocator& _alloc)
    : ok(0)  {
  (void)_alloc;
    }



   typedef int64_t _ok_type;
  _ok_type ok;





  typedef boost::shared_ptr< ::fukuro_common::OdometryServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fukuro_common::OdometryServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct OdometryServiceResponse_

typedef ::fukuro_common::OdometryServiceResponse_<std::allocator<void> > OdometryServiceResponse;

typedef boost::shared_ptr< ::fukuro_common::OdometryServiceResponse > OdometryServiceResponsePtr;
typedef boost::shared_ptr< ::fukuro_common::OdometryServiceResponse const> OdometryServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fukuro_common::OdometryServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fukuro_common::OdometryServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fukuro_common::OdometryServiceResponse_<ContainerAllocator1> & lhs, const ::fukuro_common::OdometryServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ok == rhs.ok;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fukuro_common::OdometryServiceResponse_<ContainerAllocator1> & lhs, const ::fukuro_common::OdometryServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fukuro_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::OdometryServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::OdometryServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::OdometryServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::OdometryServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::OdometryServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::OdometryServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fukuro_common::OdometryServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ffe45f316ca87fa4adf13cb9d40744eb";
  }

  static const char* value(const ::fukuro_common::OdometryServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xffe45f316ca87fa4ULL;
  static const uint64_t static_value2 = 0xadf13cb9d40744ebULL;
};

template<class ContainerAllocator>
struct DataType< ::fukuro_common::OdometryServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fukuro_common/OdometryServiceResponse";
  }

  static const char* value(const ::fukuro_common::OdometryServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fukuro_common::OdometryServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 ok\n"
;
  }

  static const char* value(const ::fukuro_common::OdometryServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fukuro_common::OdometryServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OdometryServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fukuro_common::OdometryServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fukuro_common::OdometryServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "ok: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_ODOMETRYSERVICERESPONSE_H
