// Generated by gencpp from file fukuro_common/Parameter.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_PARAMETER_H
#define FUKURO_COMMON_MESSAGE_PARAMETER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fukuro_common
{
template <class ContainerAllocator>
struct Parameter_
{
  typedef Parameter_<ContainerAllocator> Type;

  Parameter_()
    : kp(0.0)
    , ki(0.0)
    , kd(0.0)  {
    }
  Parameter_(const ContainerAllocator& _alloc)
    : kp(0.0)
    , ki(0.0)
    , kd(0.0)  {
  (void)_alloc;
    }



   typedef double _kp_type;
  _kp_type kp;

   typedef double _ki_type;
  _ki_type ki;

   typedef double _kd_type;
  _kd_type kd;





  typedef boost::shared_ptr< ::fukuro_common::Parameter_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fukuro_common::Parameter_<ContainerAllocator> const> ConstPtr;

}; // struct Parameter_

typedef ::fukuro_common::Parameter_<std::allocator<void> > Parameter;

typedef boost::shared_ptr< ::fukuro_common::Parameter > ParameterPtr;
typedef boost::shared_ptr< ::fukuro_common::Parameter const> ParameterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fukuro_common::Parameter_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fukuro_common::Parameter_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fukuro_common::Parameter_<ContainerAllocator1> & lhs, const ::fukuro_common::Parameter_<ContainerAllocator2> & rhs)
{
  return lhs.kp == rhs.kp &&
    lhs.ki == rhs.ki &&
    lhs.kd == rhs.kd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fukuro_common::Parameter_<ContainerAllocator1> & lhs, const ::fukuro_common::Parameter_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fukuro_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::Parameter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::Parameter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::Parameter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::Parameter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::Parameter_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::Parameter_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fukuro_common::Parameter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "972f4074b1c05b4e6ef321f04d38ec3f";
  }

  static const char* value(const ::fukuro_common::Parameter_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x972f4074b1c05b4eULL;
  static const uint64_t static_value2 = 0x6ef321f04d38ec3fULL;
};

template<class ContainerAllocator>
struct DataType< ::fukuro_common::Parameter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fukuro_common/Parameter";
  }

  static const char* value(const ::fukuro_common::Parameter_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fukuro_common::Parameter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 kp\n"
"float64 ki\n"
"float64 kd\n"
;
  }

  static const char* value(const ::fukuro_common::Parameter_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fukuro_common::Parameter_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.kp);
      stream.next(m.ki);
      stream.next(m.kd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Parameter_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fukuro_common::Parameter_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fukuro_common::Parameter_<ContainerAllocator>& v)
  {
    s << indent << "kp: ";
    Printer<double>::stream(s, indent + "  ", v.kp);
    s << indent << "ki: ";
    Printer<double>::stream(s, indent + "  ", v.ki);
    s << indent << "kd: ";
    Printer<double>::stream(s, indent + "  ", v.kd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_PARAMETER_H
