// Generated by gencpp from file fukuro_common/PlannerInfoSrvRequest.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_PLANNERINFOSRVREQUEST_H
#define FUKURO_COMMON_MESSAGE_PLANNERINFOSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fukuro_common
{
template <class ContainerAllocator>
struct PlannerInfoSrvRequest_
{
  typedef PlannerInfoSrvRequest_<ContainerAllocator> Type;

  PlannerInfoSrvRequest_()
    : width(0.0)
    , height(0.0)
    , grid_size(0.0)  {
    }
  PlannerInfoSrvRequest_(const ContainerAllocator& _alloc)
    : width(0.0)
    , height(0.0)
    , grid_size(0.0)  {
  (void)_alloc;
    }



   typedef double _width_type;
  _width_type width;

   typedef double _height_type;
  _height_type height;

   typedef double _grid_size_type;
  _grid_size_type grid_size;





  typedef boost::shared_ptr< ::fukuro_common::PlannerInfoSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fukuro_common::PlannerInfoSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlannerInfoSrvRequest_

typedef ::fukuro_common::PlannerInfoSrvRequest_<std::allocator<void> > PlannerInfoSrvRequest;

typedef boost::shared_ptr< ::fukuro_common::PlannerInfoSrvRequest > PlannerInfoSrvRequestPtr;
typedef boost::shared_ptr< ::fukuro_common::PlannerInfoSrvRequest const> PlannerInfoSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fukuro_common::PlannerInfoSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fukuro_common::PlannerInfoSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fukuro_common::PlannerInfoSrvRequest_<ContainerAllocator1> & lhs, const ::fukuro_common::PlannerInfoSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.grid_size == rhs.grid_size;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fukuro_common::PlannerInfoSrvRequest_<ContainerAllocator1> & lhs, const ::fukuro_common::PlannerInfoSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fukuro_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::PlannerInfoSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::PlannerInfoSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::PlannerInfoSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::PlannerInfoSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::PlannerInfoSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::PlannerInfoSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fukuro_common::PlannerInfoSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "802049f50763bc7219af4576c0df7321";
  }

  static const char* value(const ::fukuro_common::PlannerInfoSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x802049f50763bc72ULL;
  static const uint64_t static_value2 = 0x19af4576c0df7321ULL;
};

template<class ContainerAllocator>
struct DataType< ::fukuro_common::PlannerInfoSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fukuro_common/PlannerInfoSrvRequest";
  }

  static const char* value(const ::fukuro_common::PlannerInfoSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fukuro_common::PlannerInfoSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 width\n"
"float64 height\n"
"float64 grid_size\n"
;
  }

  static const char* value(const ::fukuro_common::PlannerInfoSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fukuro_common::PlannerInfoSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.grid_size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlannerInfoSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fukuro_common::PlannerInfoSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fukuro_common::PlannerInfoSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "width: ";
    Printer<double>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
    s << indent << "grid_size: ";
    Printer<double>::stream(s, indent + "  ", v.grid_size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_PLANNERINFOSRVREQUEST_H
