// Generated by gencpp from file fukuro_common/PlannerInfoSrvResponse.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_PLANNERINFOSRVRESPONSE_H
#define FUKURO_COMMON_MESSAGE_PLANNERINFOSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fukuro_common
{
template <class ContainerAllocator>
struct PlannerInfoSrvResponse_
{
  typedef PlannerInfoSrvResponse_<ContainerAllocator> Type;

  PlannerInfoSrvResponse_()
    : ok(0)  {
    }
  PlannerInfoSrvResponse_(const ContainerAllocator& _alloc)
    : ok(0)  {
  (void)_alloc;
    }



   typedef uint8_t _ok_type;
  _ok_type ok;





  typedef boost::shared_ptr< ::fukuro_common::PlannerInfoSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fukuro_common::PlannerInfoSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PlannerInfoSrvResponse_

typedef ::fukuro_common::PlannerInfoSrvResponse_<std::allocator<void> > PlannerInfoSrvResponse;

typedef boost::shared_ptr< ::fukuro_common::PlannerInfoSrvResponse > PlannerInfoSrvResponsePtr;
typedef boost::shared_ptr< ::fukuro_common::PlannerInfoSrvResponse const> PlannerInfoSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fukuro_common::PlannerInfoSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fukuro_common::PlannerInfoSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fukuro_common::PlannerInfoSrvResponse_<ContainerAllocator1> & lhs, const ::fukuro_common::PlannerInfoSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ok == rhs.ok;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fukuro_common::PlannerInfoSrvResponse_<ContainerAllocator1> & lhs, const ::fukuro_common::PlannerInfoSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fukuro_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::PlannerInfoSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::PlannerInfoSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::PlannerInfoSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::PlannerInfoSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::PlannerInfoSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::PlannerInfoSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fukuro_common::PlannerInfoSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ebb43f57b7820ff999dc120ba80eb7d8";
  }

  static const char* value(const ::fukuro_common::PlannerInfoSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xebb43f57b7820ff9ULL;
  static const uint64_t static_value2 = 0x99dc120ba80eb7d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::fukuro_common::PlannerInfoSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fukuro_common/PlannerInfoSrvResponse";
  }

  static const char* value(const ::fukuro_common::PlannerInfoSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fukuro_common::PlannerInfoSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 ok\n"
;
  }

  static const char* value(const ::fukuro_common::PlannerInfoSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fukuro_common::PlannerInfoSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlannerInfoSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fukuro_common::PlannerInfoSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fukuro_common::PlannerInfoSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_PLANNERINFOSRVRESPONSE_H
