// Generated by gencpp from file fukuro_common/PlannerServiceRequest.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_PLANNERSERVICEREQUEST_H
#define FUKURO_COMMON_MESSAGE_PLANNERSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fukuro_common
{
template <class ContainerAllocator>
struct PlannerServiceRequest_
{
  typedef PlannerServiceRequest_<ContainerAllocator> Type;

  PlannerServiceRequest_()
    : goal_x(0.0)
    , goal_y(0.0)  {
    }
  PlannerServiceRequest_(const ContainerAllocator& _alloc)
    : goal_x(0.0)
    , goal_y(0.0)  {
  (void)_alloc;
    }



   typedef double _goal_x_type;
  _goal_x_type goal_x;

   typedef double _goal_y_type;
  _goal_y_type goal_y;





  typedef boost::shared_ptr< ::fukuro_common::PlannerServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fukuro_common::PlannerServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlannerServiceRequest_

typedef ::fukuro_common::PlannerServiceRequest_<std::allocator<void> > PlannerServiceRequest;

typedef boost::shared_ptr< ::fukuro_common::PlannerServiceRequest > PlannerServiceRequestPtr;
typedef boost::shared_ptr< ::fukuro_common::PlannerServiceRequest const> PlannerServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fukuro_common::PlannerServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fukuro_common::PlannerServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fukuro_common::PlannerServiceRequest_<ContainerAllocator1> & lhs, const ::fukuro_common::PlannerServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.goal_x == rhs.goal_x &&
    lhs.goal_y == rhs.goal_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fukuro_common::PlannerServiceRequest_<ContainerAllocator1> & lhs, const ::fukuro_common::PlannerServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fukuro_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::PlannerServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::PlannerServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::PlannerServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::PlannerServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::PlannerServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::PlannerServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fukuro_common::PlannerServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13b965790a69b58a06825eaf607cdbe7";
  }

  static const char* value(const ::fukuro_common::PlannerServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13b965790a69b58aULL;
  static const uint64_t static_value2 = 0x06825eaf607cdbe7ULL;
};

template<class ContainerAllocator>
struct DataType< ::fukuro_common::PlannerServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fukuro_common/PlannerServiceRequest";
  }

  static const char* value(const ::fukuro_common::PlannerServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fukuro_common::PlannerServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 goal_x\n"
"float64 goal_y\n"
;
  }

  static const char* value(const ::fukuro_common::PlannerServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fukuro_common::PlannerServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_x);
      stream.next(m.goal_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlannerServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fukuro_common::PlannerServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fukuro_common::PlannerServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "goal_x: ";
    Printer<double>::stream(s, indent + "  ", v.goal_x);
    s << indent << "goal_y: ";
    Printer<double>::stream(s, indent + "  ", v.goal_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_PLANNERSERVICEREQUEST_H
