// Generated by gencpp from file fukuro_common/RobotControlInfo.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_ROBOTCONTROLINFO_H
#define FUKURO_COMMON_MESSAGE_ROBOTCONTROLINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace fukuro_common
{
template <class ContainerAllocator>
struct RobotControlInfo_
{
  typedef RobotControlInfo_<ContainerAllocator> Type;

  RobotControlInfo_()
    : error_radius(0.0)
    , error_angle(0.0)
    , setpoint()
    , plan(false)  {
    }
  RobotControlInfo_(const ContainerAllocator& _alloc)
    : error_radius(0.0)
    , error_angle(0.0)
    , setpoint(_alloc)
    , plan(false)  {
  (void)_alloc;
    }



   typedef double _error_radius_type;
  _error_radius_type error_radius;

   typedef double _error_angle_type;
  _error_angle_type error_angle;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _setpoint_type;
  _setpoint_type setpoint;

   typedef uint8_t _plan_type;
  _plan_type plan;





  typedef boost::shared_ptr< ::fukuro_common::RobotControlInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fukuro_common::RobotControlInfo_<ContainerAllocator> const> ConstPtr;

}; // struct RobotControlInfo_

typedef ::fukuro_common::RobotControlInfo_<std::allocator<void> > RobotControlInfo;

typedef boost::shared_ptr< ::fukuro_common::RobotControlInfo > RobotControlInfoPtr;
typedef boost::shared_ptr< ::fukuro_common::RobotControlInfo const> RobotControlInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fukuro_common::RobotControlInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fukuro_common::RobotControlInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fukuro_common::RobotControlInfo_<ContainerAllocator1> & lhs, const ::fukuro_common::RobotControlInfo_<ContainerAllocator2> & rhs)
{
  return lhs.error_radius == rhs.error_radius &&
    lhs.error_angle == rhs.error_angle &&
    lhs.setpoint == rhs.setpoint &&
    lhs.plan == rhs.plan;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fukuro_common::RobotControlInfo_<ContainerAllocator1> & lhs, const ::fukuro_common::RobotControlInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fukuro_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::RobotControlInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::RobotControlInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::RobotControlInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::RobotControlInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::RobotControlInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::RobotControlInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fukuro_common::RobotControlInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d219701cbb4b4f70bacc052c397c3a7";
  }

  static const char* value(const ::fukuro_common::RobotControlInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d219701cbb4b4f7ULL;
  static const uint64_t static_value2 = 0x0bacc052c397c3a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::fukuro_common::RobotControlInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fukuro_common/RobotControlInfo";
  }

  static const char* value(const ::fukuro_common::RobotControlInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fukuro_common::RobotControlInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 error_radius\n"
"float64 error_angle\n"
"geometry_msgs/Pose2D setpoint\n"
"bool plan\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::fukuro_common::RobotControlInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fukuro_common::RobotControlInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error_radius);
      stream.next(m.error_angle);
      stream.next(m.setpoint);
      stream.next(m.plan);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotControlInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fukuro_common::RobotControlInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fukuro_common::RobotControlInfo_<ContainerAllocator>& v)
  {
    s << indent << "error_radius: ";
    Printer<double>::stream(s, indent + "  ", v.error_radius);
    s << indent << "error_angle: ";
    Printer<double>::stream(s, indent + "  ", v.error_angle);
    s << indent << "setpoint: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.setpoint);
    s << indent << "plan: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.plan);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_ROBOTCONTROLINFO_H
