// Generated by gencpp from file fukuro_common/RobotVel.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_ROBOTVEL_H
#define FUKURO_COMMON_MESSAGE_ROBOTVEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fukuro_common
{
template <class ContainerAllocator>
struct RobotVel_
{
  typedef RobotVel_<ContainerAllocator> Type;

  RobotVel_()
    : free1(0.0)
    , free2(0.0)
    , free3(0.0)  {
    }
  RobotVel_(const ContainerAllocator& _alloc)
    : free1(0.0)
    , free2(0.0)
    , free3(0.0)  {
  (void)_alloc;
    }



   typedef float _free1_type;
  _free1_type free1;

   typedef float _free2_type;
  _free2_type free2;

   typedef float _free3_type;
  _free3_type free3;





  typedef boost::shared_ptr< ::fukuro_common::RobotVel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fukuro_common::RobotVel_<ContainerAllocator> const> ConstPtr;

}; // struct RobotVel_

typedef ::fukuro_common::RobotVel_<std::allocator<void> > RobotVel;

typedef boost::shared_ptr< ::fukuro_common::RobotVel > RobotVelPtr;
typedef boost::shared_ptr< ::fukuro_common::RobotVel const> RobotVelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fukuro_common::RobotVel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fukuro_common::RobotVel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fukuro_common::RobotVel_<ContainerAllocator1> & lhs, const ::fukuro_common::RobotVel_<ContainerAllocator2> & rhs)
{
  return lhs.free1 == rhs.free1 &&
    lhs.free2 == rhs.free2 &&
    lhs.free3 == rhs.free3;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fukuro_common::RobotVel_<ContainerAllocator1> & lhs, const ::fukuro_common::RobotVel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fukuro_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::RobotVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::RobotVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::RobotVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::RobotVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::RobotVel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::RobotVel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fukuro_common::RobotVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c8b02a70b5431ee21c709a8d3e87494";
  }

  static const char* value(const ::fukuro_common::RobotVel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c8b02a70b5431eeULL;
  static const uint64_t static_value2 = 0x21c709a8d3e87494ULL;
};

template<class ContainerAllocator>
struct DataType< ::fukuro_common::RobotVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fukuro_common/RobotVel";
  }

  static const char* value(const ::fukuro_common::RobotVel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fukuro_common::RobotVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 free1\n"
"float32 free2\n"
"float32 free3\n"
;
  }

  static const char* value(const ::fukuro_common::RobotVel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fukuro_common::RobotVel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.free1);
      stream.next(m.free2);
      stream.next(m.free3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotVel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fukuro_common::RobotVel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fukuro_common::RobotVel_<ContainerAllocator>& v)
  {
    s << indent << "free1: ";
    Printer<float>::stream(s, indent + "  ", v.free1);
    s << indent << "free2: ";
    Printer<float>::stream(s, indent + "  ", v.free2);
    s << indent << "free3: ";
    Printer<float>::stream(s, indent + "  ", v.free3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_ROBOTVEL_H
