// Generated by gencpp from file fukuro_common/SpeedTuningResponse.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_SPEEDTUNINGRESPONSE_H
#define FUKURO_COMMON_MESSAGE_SPEEDTUNINGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fukuro_common
{
template <class ContainerAllocator>
struct SpeedTuningResponse_
{
  typedef SpeedTuningResponse_<ContainerAllocator> Type;

  SpeedTuningResponse_()
    : tune_ok(false)  {
    }
  SpeedTuningResponse_(const ContainerAllocator& _alloc)
    : tune_ok(false)  {
  (void)_alloc;
    }



   typedef uint8_t _tune_ok_type;
  _tune_ok_type tune_ok;





  typedef boost::shared_ptr< ::fukuro_common::SpeedTuningResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fukuro_common::SpeedTuningResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SpeedTuningResponse_

typedef ::fukuro_common::SpeedTuningResponse_<std::allocator<void> > SpeedTuningResponse;

typedef boost::shared_ptr< ::fukuro_common::SpeedTuningResponse > SpeedTuningResponsePtr;
typedef boost::shared_ptr< ::fukuro_common::SpeedTuningResponse const> SpeedTuningResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fukuro_common::SpeedTuningResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fukuro_common::SpeedTuningResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fukuro_common::SpeedTuningResponse_<ContainerAllocator1> & lhs, const ::fukuro_common::SpeedTuningResponse_<ContainerAllocator2> & rhs)
{
  return lhs.tune_ok == rhs.tune_ok;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fukuro_common::SpeedTuningResponse_<ContainerAllocator1> & lhs, const ::fukuro_common::SpeedTuningResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fukuro_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::SpeedTuningResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::SpeedTuningResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::SpeedTuningResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::SpeedTuningResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::SpeedTuningResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::SpeedTuningResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fukuro_common::SpeedTuningResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b731fe652071ec695a1ec7ac77e39ebe";
  }

  static const char* value(const ::fukuro_common::SpeedTuningResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb731fe652071ec69ULL;
  static const uint64_t static_value2 = 0x5a1ec7ac77e39ebeULL;
};

template<class ContainerAllocator>
struct DataType< ::fukuro_common::SpeedTuningResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fukuro_common/SpeedTuningResponse";
  }

  static const char* value(const ::fukuro_common::SpeedTuningResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fukuro_common::SpeedTuningResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool tune_ok\n"
;
  }

  static const char* value(const ::fukuro_common::SpeedTuningResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fukuro_common::SpeedTuningResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tune_ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpeedTuningResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fukuro_common::SpeedTuningResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fukuro_common::SpeedTuningResponse_<ContainerAllocator>& v)
  {
    s << indent << "tune_ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tune_ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_SPEEDTUNINGRESPONSE_H
