// Generated by gencpp from file fukuro_common/StaticObstacles.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_STATICOBSTACLES_H
#define FUKURO_COMMON_MESSAGE_STATICOBSTACLES_H

#include <ros/service_traits.h>


#include <fukuro_common/StaticObstaclesRequest.h>
#include <fukuro_common/StaticObstaclesResponse.h>


namespace fukuro_common
{

struct StaticObstacles
{

typedef StaticObstaclesRequest Request;
typedef StaticObstaclesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StaticObstacles
} // namespace fukuro_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fukuro_common::StaticObstacles > {
  static const char* value()
  {
    return "d9e5d5b887b6aabe5a57861e1897da91";
  }

  static const char* value(const ::fukuro_common::StaticObstacles&) { return value(); }
};

template<>
struct DataType< ::fukuro_common::StaticObstacles > {
  static const char* value()
  {
    return "fukuro_common/StaticObstacles";
  }

  static const char* value(const ::fukuro_common::StaticObstacles&) { return value(); }
};


// service_traits::MD5Sum< ::fukuro_common::StaticObstaclesRequest> should match
// service_traits::MD5Sum< ::fukuro_common::StaticObstacles >
template<>
struct MD5Sum< ::fukuro_common::StaticObstaclesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fukuro_common::StaticObstacles >::value();
  }
  static const char* value(const ::fukuro_common::StaticObstaclesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fukuro_common::StaticObstaclesRequest> should match
// service_traits::DataType< ::fukuro_common::StaticObstacles >
template<>
struct DataType< ::fukuro_common::StaticObstaclesRequest>
{
  static const char* value()
  {
    return DataType< ::fukuro_common::StaticObstacles >::value();
  }
  static const char* value(const ::fukuro_common::StaticObstaclesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fukuro_common::StaticObstaclesResponse> should match
// service_traits::MD5Sum< ::fukuro_common::StaticObstacles >
template<>
struct MD5Sum< ::fukuro_common::StaticObstaclesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fukuro_common::StaticObstacles >::value();
  }
  static const char* value(const ::fukuro_common::StaticObstaclesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fukuro_common::StaticObstaclesResponse> should match
// service_traits::DataType< ::fukuro_common::StaticObstacles >
template<>
struct DataType< ::fukuro_common::StaticObstaclesResponse>
{
  static const char* value()
  {
    return DataType< ::fukuro_common::StaticObstacles >::value();
  }
  static const char* value(const ::fukuro_common::StaticObstaclesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_STATICOBSTACLES_H
