// Generated by gencpp from file fukuro_common/Whites.msg
// DO NOT EDIT!


#ifndef FUKURO_COMMON_MESSAGE_WHITES_H
#define FUKURO_COMMON_MESSAGE_WHITES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <fukuro_common/Point2d.h>

namespace fukuro_common
{
template <class ContainerAllocator>
struct Whites_
{
  typedef Whites_<ContainerAllocator> Type;

  Whites_()
    : whites()  {
    }
  Whites_(const ContainerAllocator& _alloc)
    : whites(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::fukuro_common::Point2d_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::fukuro_common::Point2d_<ContainerAllocator> >::other >  _whites_type;
  _whites_type whites;





  typedef boost::shared_ptr< ::fukuro_common::Whites_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fukuro_common::Whites_<ContainerAllocator> const> ConstPtr;

}; // struct Whites_

typedef ::fukuro_common::Whites_<std::allocator<void> > Whites;

typedef boost::shared_ptr< ::fukuro_common::Whites > WhitesPtr;
typedef boost::shared_ptr< ::fukuro_common::Whites const> WhitesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fukuro_common::Whites_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fukuro_common::Whites_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fukuro_common::Whites_<ContainerAllocator1> & lhs, const ::fukuro_common::Whites_<ContainerAllocator2> & rhs)
{
  return lhs.whites == rhs.whites;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fukuro_common::Whites_<ContainerAllocator1> & lhs, const ::fukuro_common::Whites_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fukuro_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::Whites_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fukuro_common::Whites_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::Whites_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fukuro_common::Whites_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::Whites_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fukuro_common::Whites_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fukuro_common::Whites_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3888bbcb4197c33e8f1471d84dc66374";
  }

  static const char* value(const ::fukuro_common::Whites_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3888bbcb4197c33eULL;
  static const uint64_t static_value2 = 0x8f1471d84dc66374ULL;
};

template<class ContainerAllocator>
struct DataType< ::fukuro_common::Whites_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fukuro_common/Whites";
  }

  static const char* value(const ::fukuro_common::Whites_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fukuro_common::Whites_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Point2d[] whites\n"
"================================================================================\n"
"MSG: fukuro_common/Point2d\n"
"float64 x\n"
"float64 y\n"
;
  }

  static const char* value(const ::fukuro_common::Whites_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fukuro_common::Whites_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.whites);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Whites_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fukuro_common::Whites_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fukuro_common::Whites_<ContainerAllocator>& v)
  {
    s << indent << "whites[]" << std::endl;
    for (size_t i = 0; i < v.whites.size(); ++i)
    {
      s << indent << "  whites[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::fukuro_common::Point2d_<ContainerAllocator> >::stream(s, indent + "    ", v.whites[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FUKURO_COMMON_MESSAGE_WHITES_H
