# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fukuro_common/Localization.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Localization(genpy.Message):
  _md5sum = "d25fba6248365fe1c093e492c489b9fd"
  _type = "fukuro_common/Localization"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Pose2D estimate_pos
geometry_msgs/Pose2D estimate_pos_descrete
geometry_msgs/Pose2D[] particles
geometry_msgs/Pose2D best_estimation
float64[] weights
float64 best_estimation_weight
int32 grid_size

================================================================================
MSG: geometry_msgs/Pose2D
# Deprecated
# Please use the full 3D pose.

# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.

# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.


# This expresses a position and orientation on a 2D manifold.

float64 x
float64 y
float64 theta
"""
  __slots__ = ['estimate_pos','estimate_pos_descrete','particles','best_estimation','weights','best_estimation_weight','grid_size']
  _slot_types = ['geometry_msgs/Pose2D','geometry_msgs/Pose2D','geometry_msgs/Pose2D[]','geometry_msgs/Pose2D','float64[]','float64','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       estimate_pos,estimate_pos_descrete,particles,best_estimation,weights,best_estimation_weight,grid_size

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Localization, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.estimate_pos is None:
        self.estimate_pos = geometry_msgs.msg.Pose2D()
      if self.estimate_pos_descrete is None:
        self.estimate_pos_descrete = geometry_msgs.msg.Pose2D()
      if self.particles is None:
        self.particles = []
      if self.best_estimation is None:
        self.best_estimation = geometry_msgs.msg.Pose2D()
      if self.weights is None:
        self.weights = []
      if self.best_estimation_weight is None:
        self.best_estimation_weight = 0.
      if self.grid_size is None:
        self.grid_size = 0
    else:
      self.estimate_pos = geometry_msgs.msg.Pose2D()
      self.estimate_pos_descrete = geometry_msgs.msg.Pose2D()
      self.particles = []
      self.best_estimation = geometry_msgs.msg.Pose2D()
      self.weights = []
      self.best_estimation_weight = 0.
      self.grid_size = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.estimate_pos.x, _x.estimate_pos.y, _x.estimate_pos.theta, _x.estimate_pos_descrete.x, _x.estimate_pos_descrete.y, _x.estimate_pos_descrete.theta))
      length = len(self.particles)
      buff.write(_struct_I.pack(length))
      for val1 in self.particles:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
      _x = self
      buff.write(_get_struct_3d().pack(_x.best_estimation.x, _x.best_estimation.y, _x.best_estimation.theta))
      length = len(self.weights)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.weights))
      _x = self
      buff.write(_get_struct_di().pack(_x.best_estimation_weight, _x.grid_size))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.estimate_pos is None:
        self.estimate_pos = geometry_msgs.msg.Pose2D()
      if self.estimate_pos_descrete is None:
        self.estimate_pos_descrete = geometry_msgs.msg.Pose2D()
      if self.particles is None:
        self.particles = None
      if self.best_estimation is None:
        self.best_estimation = geometry_msgs.msg.Pose2D()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.estimate_pos.x, _x.estimate_pos.y, _x.estimate_pos.theta, _x.estimate_pos_descrete.x, _x.estimate_pos_descrete.y, _x.estimate_pos_descrete.theta,) = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.particles = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
        self.particles.append(val1)
      _x = self
      start = end
      end += 24
      (_x.best_estimation.x, _x.best_estimation.y, _x.best_estimation.theta,) = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.weights = s.unpack(str[start:end])
      _x = self
      start = end
      end += 12
      (_x.best_estimation_weight, _x.grid_size,) = _get_struct_di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.estimate_pos.x, _x.estimate_pos.y, _x.estimate_pos.theta, _x.estimate_pos_descrete.x, _x.estimate_pos_descrete.y, _x.estimate_pos_descrete.theta))
      length = len(self.particles)
      buff.write(_struct_I.pack(length))
      for val1 in self.particles:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
      _x = self
      buff.write(_get_struct_3d().pack(_x.best_estimation.x, _x.best_estimation.y, _x.best_estimation.theta))
      length = len(self.weights)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.weights.tostring())
      _x = self
      buff.write(_get_struct_di().pack(_x.best_estimation_weight, _x.grid_size))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.estimate_pos is None:
        self.estimate_pos = geometry_msgs.msg.Pose2D()
      if self.estimate_pos_descrete is None:
        self.estimate_pos_descrete = geometry_msgs.msg.Pose2D()
      if self.particles is None:
        self.particles = None
      if self.best_estimation is None:
        self.best_estimation = geometry_msgs.msg.Pose2D()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.estimate_pos.x, _x.estimate_pos.y, _x.estimate_pos.theta, _x.estimate_pos_descrete.x, _x.estimate_pos_descrete.y, _x.estimate_pos_descrete.theta,) = _get_struct_6d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.particles = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
        self.particles.append(val1)
      _x = self
      start = end
      end += 24
      (_x.best_estimation.x, _x.best_estimation.y, _x.best_estimation.theta,) = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.weights = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      _x = self
      start = end
      end += 12
      (_x.best_estimation_weight, _x.grid_size,) = _get_struct_di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
_struct_di = None
def _get_struct_di():
    global _struct_di
    if _struct_di is None:
        _struct_di = struct.Struct("<di")
    return _struct_di
