# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fukuro_common/Obstacle.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import fukuro_common.msg

class Obstacle(genpy.Message):
  _md5sum = "204658f3eba3518a7ff5338be777b1e8"
  _type = "fukuro_common/Obstacle"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Point2d pos
float64 r
int8 shape
================================================================================
MSG: fukuro_common/Point2d
float64 x
float64 y"""
  __slots__ = ['pos','r','shape']
  _slot_types = ['fukuro_common/Point2d','float64','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pos,r,shape

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Obstacle, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.pos is None:
        self.pos = fukuro_common.msg.Point2d()
      if self.r is None:
        self.r = 0.
      if self.shape is None:
        self.shape = 0
    else:
      self.pos = fukuro_common.msg.Point2d()
      self.r = 0.
      self.shape = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3db().pack(_x.pos.x, _x.pos.y, _x.r, _x.shape))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pos is None:
        self.pos = fukuro_common.msg.Point2d()
      end = 0
      _x = self
      start = end
      end += 25
      (_x.pos.x, _x.pos.y, _x.r, _x.shape,) = _get_struct_3db().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3db().pack(_x.pos.x, _x.pos.y, _x.r, _x.shape))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pos is None:
        self.pos = fukuro_common.msg.Point2d()
      end = 0
      _x = self
      start = end
      end += 25
      (_x.pos.x, _x.pos.y, _x.r, _x.shape,) = _get_struct_3db().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3db = None
def _get_struct_3db():
    global _struct_3db
    if _struct_3db is None:
        _struct_3db = struct.Struct("<3db")
    return _struct_3db
