# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fukuro_common/StaticObstacle.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import fukuro_common.msg

class StaticObstacle(genpy.Message):
  _md5sum = "46d3fb587aed8a021e47dcb530b200ee"
  _type = "fukuro_common/StaticObstacle"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Obstacle obstacle1
Obstacle obstacle2
Obstacle obstacle3
Obstacle obstacle4
Obstacle obstacle5
Obstacle obstacle6
Obstacle obstacle7
Obstacle obstacle8
================================================================================
MSG: fukuro_common/Obstacle
Point2d pos
float64 r
int8 shape
================================================================================
MSG: fukuro_common/Point2d
float64 x
float64 y"""
  __slots__ = ['obstacle1','obstacle2','obstacle3','obstacle4','obstacle5','obstacle6','obstacle7','obstacle8']
  _slot_types = ['fukuro_common/Obstacle','fukuro_common/Obstacle','fukuro_common/Obstacle','fukuro_common/Obstacle','fukuro_common/Obstacle','fukuro_common/Obstacle','fukuro_common/Obstacle','fukuro_common/Obstacle']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       obstacle1,obstacle2,obstacle3,obstacle4,obstacle5,obstacle6,obstacle7,obstacle8

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(StaticObstacle, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.obstacle1 is None:
        self.obstacle1 = fukuro_common.msg.Obstacle()
      if self.obstacle2 is None:
        self.obstacle2 = fukuro_common.msg.Obstacle()
      if self.obstacle3 is None:
        self.obstacle3 = fukuro_common.msg.Obstacle()
      if self.obstacle4 is None:
        self.obstacle4 = fukuro_common.msg.Obstacle()
      if self.obstacle5 is None:
        self.obstacle5 = fukuro_common.msg.Obstacle()
      if self.obstacle6 is None:
        self.obstacle6 = fukuro_common.msg.Obstacle()
      if self.obstacle7 is None:
        self.obstacle7 = fukuro_common.msg.Obstacle()
      if self.obstacle8 is None:
        self.obstacle8 = fukuro_common.msg.Obstacle()
    else:
      self.obstacle1 = fukuro_common.msg.Obstacle()
      self.obstacle2 = fukuro_common.msg.Obstacle()
      self.obstacle3 = fukuro_common.msg.Obstacle()
      self.obstacle4 = fukuro_common.msg.Obstacle()
      self.obstacle5 = fukuro_common.msg.Obstacle()
      self.obstacle6 = fukuro_common.msg.Obstacle()
      self.obstacle7 = fukuro_common.msg.Obstacle()
      self.obstacle8 = fukuro_common.msg.Obstacle()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3db3db3db3db3db3db3db3db().pack(_x.obstacle1.pos.x, _x.obstacle1.pos.y, _x.obstacle1.r, _x.obstacle1.shape, _x.obstacle2.pos.x, _x.obstacle2.pos.y, _x.obstacle2.r, _x.obstacle2.shape, _x.obstacle3.pos.x, _x.obstacle3.pos.y, _x.obstacle3.r, _x.obstacle3.shape, _x.obstacle4.pos.x, _x.obstacle4.pos.y, _x.obstacle4.r, _x.obstacle4.shape, _x.obstacle5.pos.x, _x.obstacle5.pos.y, _x.obstacle5.r, _x.obstacle5.shape, _x.obstacle6.pos.x, _x.obstacle6.pos.y, _x.obstacle6.r, _x.obstacle6.shape, _x.obstacle7.pos.x, _x.obstacle7.pos.y, _x.obstacle7.r, _x.obstacle7.shape, _x.obstacle8.pos.x, _x.obstacle8.pos.y, _x.obstacle8.r, _x.obstacle8.shape))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.obstacle1 is None:
        self.obstacle1 = fukuro_common.msg.Obstacle()
      if self.obstacle2 is None:
        self.obstacle2 = fukuro_common.msg.Obstacle()
      if self.obstacle3 is None:
        self.obstacle3 = fukuro_common.msg.Obstacle()
      if self.obstacle4 is None:
        self.obstacle4 = fukuro_common.msg.Obstacle()
      if self.obstacle5 is None:
        self.obstacle5 = fukuro_common.msg.Obstacle()
      if self.obstacle6 is None:
        self.obstacle6 = fukuro_common.msg.Obstacle()
      if self.obstacle7 is None:
        self.obstacle7 = fukuro_common.msg.Obstacle()
      if self.obstacle8 is None:
        self.obstacle8 = fukuro_common.msg.Obstacle()
      end = 0
      _x = self
      start = end
      end += 200
      (_x.obstacle1.pos.x, _x.obstacle1.pos.y, _x.obstacle1.r, _x.obstacle1.shape, _x.obstacle2.pos.x, _x.obstacle2.pos.y, _x.obstacle2.r, _x.obstacle2.shape, _x.obstacle3.pos.x, _x.obstacle3.pos.y, _x.obstacle3.r, _x.obstacle3.shape, _x.obstacle4.pos.x, _x.obstacle4.pos.y, _x.obstacle4.r, _x.obstacle4.shape, _x.obstacle5.pos.x, _x.obstacle5.pos.y, _x.obstacle5.r, _x.obstacle5.shape, _x.obstacle6.pos.x, _x.obstacle6.pos.y, _x.obstacle6.r, _x.obstacle6.shape, _x.obstacle7.pos.x, _x.obstacle7.pos.y, _x.obstacle7.r, _x.obstacle7.shape, _x.obstacle8.pos.x, _x.obstacle8.pos.y, _x.obstacle8.r, _x.obstacle8.shape,) = _get_struct_3db3db3db3db3db3db3db3db().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3db3db3db3db3db3db3db3db().pack(_x.obstacle1.pos.x, _x.obstacle1.pos.y, _x.obstacle1.r, _x.obstacle1.shape, _x.obstacle2.pos.x, _x.obstacle2.pos.y, _x.obstacle2.r, _x.obstacle2.shape, _x.obstacle3.pos.x, _x.obstacle3.pos.y, _x.obstacle3.r, _x.obstacle3.shape, _x.obstacle4.pos.x, _x.obstacle4.pos.y, _x.obstacle4.r, _x.obstacle4.shape, _x.obstacle5.pos.x, _x.obstacle5.pos.y, _x.obstacle5.r, _x.obstacle5.shape, _x.obstacle6.pos.x, _x.obstacle6.pos.y, _x.obstacle6.r, _x.obstacle6.shape, _x.obstacle7.pos.x, _x.obstacle7.pos.y, _x.obstacle7.r, _x.obstacle7.shape, _x.obstacle8.pos.x, _x.obstacle8.pos.y, _x.obstacle8.r, _x.obstacle8.shape))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.obstacle1 is None:
        self.obstacle1 = fukuro_common.msg.Obstacle()
      if self.obstacle2 is None:
        self.obstacle2 = fukuro_common.msg.Obstacle()
      if self.obstacle3 is None:
        self.obstacle3 = fukuro_common.msg.Obstacle()
      if self.obstacle4 is None:
        self.obstacle4 = fukuro_common.msg.Obstacle()
      if self.obstacle5 is None:
        self.obstacle5 = fukuro_common.msg.Obstacle()
      if self.obstacle6 is None:
        self.obstacle6 = fukuro_common.msg.Obstacle()
      if self.obstacle7 is None:
        self.obstacle7 = fukuro_common.msg.Obstacle()
      if self.obstacle8 is None:
        self.obstacle8 = fukuro_common.msg.Obstacle()
      end = 0
      _x = self
      start = end
      end += 200
      (_x.obstacle1.pos.x, _x.obstacle1.pos.y, _x.obstacle1.r, _x.obstacle1.shape, _x.obstacle2.pos.x, _x.obstacle2.pos.y, _x.obstacle2.r, _x.obstacle2.shape, _x.obstacle3.pos.x, _x.obstacle3.pos.y, _x.obstacle3.r, _x.obstacle3.shape, _x.obstacle4.pos.x, _x.obstacle4.pos.y, _x.obstacle4.r, _x.obstacle4.shape, _x.obstacle5.pos.x, _x.obstacle5.pos.y, _x.obstacle5.r, _x.obstacle5.shape, _x.obstacle6.pos.x, _x.obstacle6.pos.y, _x.obstacle6.r, _x.obstacle6.shape, _x.obstacle7.pos.x, _x.obstacle7.pos.y, _x.obstacle7.r, _x.obstacle7.shape, _x.obstacle8.pos.x, _x.obstacle8.pos.y, _x.obstacle8.r, _x.obstacle8.shape,) = _get_struct_3db3db3db3db3db3db3db3db().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3db3db3db3db3db3db3db3db = None
def _get_struct_3db3db3db3db3db3db3db3db():
    global _struct_3db3db3db3db3db3db3db3db
    if _struct_3db3db3db3db3db3db3db3db is None:
        _struct_3db3db3db3db3db3db3db3db = struct.Struct("<3db3db3db3db3db3db3db3db")
    return _struct_3db3db3db3db3db3db3db3db
