# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fukuro_common/Teammates.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Teammates(genpy.Message):
  _md5sum = "9d9d85ad8ed32eac7013d69f18ea4e63"
  _type = "fukuro_common/Teammates"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 robotnumber
geometry_msgs/Pose2D[] pose
bool[] available
int32 behavior
int32 state
bool isConnected
bool isManualPositioning
bool isBallOwn
bool[] pass_ball
bool[] receive_ball
================================================================================
MSG: geometry_msgs/Pose2D
# Deprecated
# Please use the full 3D pose.

# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.

# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.


# This expresses a position and orientation on a 2D manifold.

float64 x
float64 y
float64 theta
"""
  __slots__ = ['robotnumber','pose','available','behavior','state','isConnected','isManualPositioning','isBallOwn','pass_ball','receive_ball']
  _slot_types = ['int32','geometry_msgs/Pose2D[]','bool[]','int32','int32','bool','bool','bool','bool[]','bool[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       robotnumber,pose,available,behavior,state,isConnected,isManualPositioning,isBallOwn,pass_ball,receive_ball

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Teammates, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.robotnumber is None:
        self.robotnumber = 0
      if self.pose is None:
        self.pose = []
      if self.available is None:
        self.available = []
      if self.behavior is None:
        self.behavior = 0
      if self.state is None:
        self.state = 0
      if self.isConnected is None:
        self.isConnected = False
      if self.isManualPositioning is None:
        self.isManualPositioning = False
      if self.isBallOwn is None:
        self.isBallOwn = False
      if self.pass_ball is None:
        self.pass_ball = []
      if self.receive_ball is None:
        self.receive_ball = []
    else:
      self.robotnumber = 0
      self.pose = []
      self.available = []
      self.behavior = 0
      self.state = 0
      self.isConnected = False
      self.isManualPositioning = False
      self.isBallOwn = False
      self.pass_ball = []
      self.receive_ball = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.robotnumber
      buff.write(_get_struct_i().pack(_x))
      length = len(self.pose)
      buff.write(_struct_I.pack(length))
      for val1 in self.pose:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
      length = len(self.available)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.Struct(pattern).pack(*self.available))
      _x = self
      buff.write(_get_struct_2i3B().pack(_x.behavior, _x.state, _x.isConnected, _x.isManualPositioning, _x.isBallOwn))
      length = len(self.pass_ball)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.Struct(pattern).pack(*self.pass_ball))
      length = len(self.receive_ball)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.Struct(pattern).pack(*self.receive_ball))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose is None:
        self.pose = None
      end = 0
      start = end
      end += 4
      (self.robotnumber,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.pose = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
        self.pose.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.available = s.unpack(str[start:end])
      self.available = list(map(bool, self.available))
      _x = self
      start = end
      end += 11
      (_x.behavior, _x.state, _x.isConnected, _x.isManualPositioning, _x.isBallOwn,) = _get_struct_2i3B().unpack(str[start:end])
      self.isConnected = bool(self.isConnected)
      self.isManualPositioning = bool(self.isManualPositioning)
      self.isBallOwn = bool(self.isBallOwn)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.pass_ball = s.unpack(str[start:end])
      self.pass_ball = list(map(bool, self.pass_ball))
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.receive_ball = s.unpack(str[start:end])
      self.receive_ball = list(map(bool, self.receive_ball))
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.robotnumber
      buff.write(_get_struct_i().pack(_x))
      length = len(self.pose)
      buff.write(_struct_I.pack(length))
      for val1 in self.pose:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
      length = len(self.available)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.available.tostring())
      _x = self
      buff.write(_get_struct_2i3B().pack(_x.behavior, _x.state, _x.isConnected, _x.isManualPositioning, _x.isBallOwn))
      length = len(self.pass_ball)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.pass_ball.tostring())
      length = len(self.receive_ball)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.receive_ball.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose is None:
        self.pose = None
      end = 0
      start = end
      end += 4
      (self.robotnumber,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.pose = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
        self.pose.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.available = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.available = list(map(bool, self.available))
      _x = self
      start = end
      end += 11
      (_x.behavior, _x.state, _x.isConnected, _x.isManualPositioning, _x.isBallOwn,) = _get_struct_2i3B().unpack(str[start:end])
      self.isConnected = bool(self.isConnected)
      self.isManualPositioning = bool(self.isManualPositioning)
      self.isBallOwn = bool(self.isBallOwn)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.pass_ball = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.pass_ball = list(map(bool, self.pass_ball))
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.receive_ball = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.receive_ball = list(map(bool, self.receive_ball))
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i3B = None
def _get_struct_2i3B():
    global _struct_2i3B
    if _struct_2i3B is None:
        _struct_2i3B = struct.Struct("<2i3B")
    return _struct_2i3B
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
